{
	"RPT_BUILDER_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?",

    "LINK_NULLABLE_DEFAULT": "Default",
    "LINK_NULLABLE_RIGHT": "Parent",
    "LINK_NULLABLE_LEFT": "Child",
    "LINK_NULLABLE_NONE": "None",
	
	"FILTERS_LABEL_EQUALS":"Equals",
	"FILTERS_LABEL_LIKE": "Contains Matching substring",
	"FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
	"FILTERS_LABEL_GREATER_THAN": "Greater than",
	"FILTERS_LABEL_GT_TIME": "After (Date/Time)",
	"FILTERS_LABEL_GT_EQUAL": "Greater than or equal to",
	"FILTERS_LABEL_GTE_TIME": "On or After (Date/Time)",
	"FILTERS_LABEL_LESS_THAN": "Less than",
	"FILTERS_LABEL_LT_TIME": "Before (Date/Time)",
	"FILTERS_LABEL_LT_EQUAL": "Less than or equal to",
	"FILTERS_LABEL_LSE_TIME": "On or Before (Date/Time)",
	"FILTERS_LABEL_IN": "In list",
	"FILTERS_LABEL_NOT_IN": "Not in list",
	"FILTERS_LABEL_BETWEEN": "Between",
	"FILTERS_LABEL_NOT_BETWEEN": "Not between",
	"FILTERS_LABEL_NULL": "Is NULL",
	"FILTERS_LABEL_NOT_NULL": "Is not NULL",
	"FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank",
	"FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank",
	
	"FOLDERS_TEMPLATES": "Templates",
	"FOLDERS_TEMPLATE": "Template",
	"FOLDERS_REPORTS": "Reports",
	"FOLDERS_REPORT": "Report",
	"FOLDERS_OUTPUT": "Output",
	
	"FOLDER_WINDOW_SELECT_ITEM": "Please select an item from the list",
	"FOLDER_WINDOW_CHANGE_FOLDERS": "Change Folders",
	"FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}",
	"FOLDER_WINDOW_COLNAME_SELECT": "Select",
	"FOLDER_WINDOW_COLNAME_ALL": "All",
	"FOLDER_WINDOW_COLNAME_NONE": "None",
	
	"REPORT_EDITOR_REPORT_FOLDERS": "Report Folders",
	"REPORT_EDITOR_OUTPUT_FOLDERS": "Output Folders",
	"REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
	"REPORT_EDITOR_ENTER_NAME_ALERT": "Please enter a report name",
	"REPORT_EDITOR_INVALID_DATE_ALERT": "invalid start date -  YYYY-MM-DD",
	"REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
	
	"TFORMS_LABEL_RAW_DATA": "Raw Data",
	"TFORMS_LABEL_FIRST": "First Value",
	"TFORMS_LABEL_LAST": "Last Value",
	"TFORMS_LABEL_COUNT": "Count",
	"TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct",
	"TFORMS_LABEL_MIN": "Min",
	"TFORMS_LABEL_MAX": "Max",
	"TFORMS_LABEL_LOWER": "Lower case",
	"TFORMS_LABEL_UPPER": "Upper case",
	"TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)",
	"TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
	"TFORMS_LABEL_DOW": "Day of Week",
	"TFORMS_LABEL_DOM": "Day of Month",
	"TFORMS_LABEL_DOY": "Day of Year",
	"TFORMS_LABEL_WOY": "Week of Year",
	"TFORMS_LABEL_MOY": "Month of Year",
	"TFORMS_LABEL_QOY": "Quarter of Year",
	"TFORMS_LABEL_HOD": "Hour of day",
	"TFORMS_LABEL_DATE": "Date",
	"TFORMS_LABEL_MONTH_TRUNC": "Year + Month",
	"TFORMS_LABEL_YEAR_TRUNC": "Year",
	"TFORMS_LABEL_HOUR_TRUNC": "Hour",
	"TFORMS_LABEL_DAY_NAME": "Day Name",
	"TFORMS_LABEL_MONTH_NAME": "Month Name'",
	"TFORMS_LABEL_AGE": "Age",
	"TFORMS_LABEL_MONTHS_AGO": "Months ago",
	"TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
	"TFORMS_LABEL_SUM": "Sum",
	"TFORMS_LABEL_AVERAGE": "Average",
	"TFORMS_LABEL_ROUND": "Round",
	"TFORMS_LABEL_INT": "Drop trailing decimals",
	
	"WIDGET_DAYS": "Day(s)",
	"WIDGET_MONTHS": "Month(s)",
	"WIDGET_YEARS": "Year(s)",
	"WIDGET_QUARTERS": "Quarter(s)",
	"WIDGET_REAL_DATE": "Real Date",
	"WIDGET_RELATIVE_DATE": "Relative Date",
	
	"OPERATORS_EQUALS": "Equals",
	"OPERATORS_LIKE": "Contains Matching substring",
	"OPERATORS_ILIKE": "Contains Matching substring (ignore case)",
	"OPERATORS_GREATER_THAN": "Greater than",
	"OPERATORS_GT_TIME": "After (Date/Time)",
	"OPERATORS_GT_EQUAL": "Greater than or equal to",
	"OPERATORS_GTE_TIME": "On or After (Date/Time)",
	"OPERATORS_LESS_THAN": "Less than",
	"OPERATORS_LT_TIME": "Before (Date/Time)",
	"OPERATORS_LT_EQUAL": "Less than or equal to",
	"OPERATORS_LTE_TIME": "On or Before (Date/Time)",
	"OPERATORS_IN_LIST": "In list",
	"OPERATORS_NOT_IN_LIST": "Not in list",
	"OPERATORS_BETWEEN": "Between",
	"OPERATORS_NOT_BETWEEN": "Not between",
	"OPERATORS_IS_NULL": "Is NULL",
	"OPERATORS_IS_NOT_NULL": "Is not NULL",
	"OPERATORS_NULL_BLANK": "Is NULL or Blank",
	"OPERATORS_NOT_NULL_BLANK": "Is not NULL or Blank",
	
	"SOURCE_BROWSE_AGGREGATE": "Aggregate",
	"SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate",
	
	"SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?",
	"SOURCE_SETUP_CORE_SOURCES": "Core Sources",
	"SOURCE_SETUP_ALL_AVAIL_SOURCES": "All Available Sources",
	
	"TEMPLATE_CONF_BARE": "Bare",
	"TEMPLATE_CONF_RAW_DATA": "Raw Data",
	"TEMPLATE_CONF_EQUALS": "Equals",
	"TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.",
	"TEMPLATE_CONF_PROMPT_CHANGE": "Change the column header to: ${0}",
	"TEMPLATE_CONF_BOOLEAN_VALUE": "Boolean Value",
	"TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:",
	"TEMPLATE_CONF_TRUE": "True",
	"TEMPLATE_CONF_FALSE": "False",
	"TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.",
	"TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):",
	"TEMPLATE_CONF_NOT_BETWEEN": "Field value is not between (comma separated):",
	"TEMPLATE_CONF_BETWEEN": "Field value is between (comma separated):",
	"TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):",
	"TEMPLATE_CONF_IN": "Field matches one of list (comma separated):",
	"TEMPLATE_CONF_DEFAULT": "Value ${0}:",
	"TEMPLATE_CONF_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?",
	"TEMPLATE_CONF_SUCCESS_SAVE": "Template ${0} was successfully saved.",
	
	"TRANSFORMS_BARE": "Raw Data",
	"TRANSFORMS_FIRST": "First Value",
	"TRANSFORMS_LAST": "Last Value",
	"TRANSFORMS_COUNT": "Count",
	"TRANSFORMS_COUNT_DISTINCT": "Count Distinct",
	"TRANSFORMS_MIN": "Min",
	"TRANSFORMS_MAX": "Max",
	"TRANSFORMS_SUBSTRING": "Substring",
	"TRANSFORMS_LOWER": "Lower case",
	"TRANSFORMS_UPPER": "Upper case",
	"TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)",
	"TRANSFORMS_FIRST_WORD": "First contiguous non-space string",
	"TRANSFORMS_DOW": "Day of Week",
	"TRANSFORMS_DOM": "Day of Month",
	"TRANSFORMS_DOY": "Day of Year",
	"TRANSFORMS_WOY": "Week of Year",
	"TRANSFORMS_MOY": "Month of Year",
	"TRANSFORMS_QOY": "Quarter of Year",
	"TRANSFORMS_HOD": "Hour of day",
	"TRANSFORMS_DATE": "Date",
	"TRANSFORMS_MONTH_TRUNC": "Year + Month",
	"TRANSFORMS_YEAR_TRUNC": "Year",
	"TRANSFORMS_HOUR_TRUNC": "Hour",
	"TRANSFORMS_DAY_NAME": "Day Name",
	"TRANSFORMS_MONTH_NAME": "Month Name",
	"TRANSFORMS_AGE": "Age",
	"TRANSFORMS_MONTHS_AGO": "Months ago",
	"TRANSFORMS_QUARTERS_AGO": "Quarters ago",
	"TRANSFORMS_SUM": "Sum",
	"TRANSFORMS_AVERAGE": "Average",
	"TRANSFORMS_ROUND": "Round",
	"TRANSFORMS_INT": "Drop trailing decimals"
}
