{
	"RPT_BUILDER_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?",
	
	"FILTERS_LABEL_EQUALS":"Equals",
	"FILTERS_LABEL_LIKE": "Contains Matching substring",
	"FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)",
	"FILTERS_LABEL_GREATER_THAN": "Greater than",
	"FILTERS_LABEL_GT_TIME": "After (Date/Time)",
	"FILTERS_LABEL_GT_EQUAL": "Greater than or equal to",
	"FILTERS_LABEL_GTE_TIME": "On or After (Date/Time)",
	"FILTERS_LABEL_LESS_THAN": "Less than",
	"FILTERS_LABEL_LT_TIME": "Before (Date/Time)",
	"FILTERS_LABEL_LT_EQUAL": "Less than or equal to",
	"FILTERS_LABEL_LSE_TIME": "On or Before (Date/Time)",
	"FILTERS_LABEL_IN": "In list",
	"FILTERS_LABEL_NOT_IN": "Not in list",
	"FILTERS_LABEL_BETWEEN": "Between",
	"FILTERS_LABEL_NOT_BETWEEN": "Not between",
	"FILTERS_LABEL_NULL": "Is NULL",
	"FILTERS_LABEL_NOT_NULL": "Is not NULL",
	"FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank",
	"FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank",
	
	"FOLDERS_TEMPLATES": "Templates",
	"FOLDERS_TEMPLATE": "Template",
	"FOLDERS_REPORTS": "Reports",
	"FOLDERS_REPORT": "Report",
	"FOLDERS_OUTPUT": "Output",
	
	"FOLDER_WINDOW_SELECT_ITEM": "Please select an item from the list",
	"FOLDER_WINDOW_CHANGE_FOLDERS": "Change Folders",
	"FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}",
	"FOLDER_WINDOW_COLNAME_SELECT": "Select",
	"FOLDER_WINDOW_COLNAME_ALL": "All",
	"FOLDER_WINDOW_COLNAME_NONE": "None",
	
	"REPORT_EDITOR_REPORT_FOLDERS": "Report Folders",
	"REPORT_EDITOR_OUTPUT_FOLDERS": "Output Folders",
	"REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder",
	"REPORT_EDITOR_ENTER_NAME_ALERT": "Please enter a report name",
	"REPORT_EDITOR_INVALID_DATE_ALERT": "invalid start date -  YYYY-MM-DD",
	"REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder",
	
	"TFORMS_LABEL_RAW_DATA": "Raw Data",
	"TFORMS_LABEL_FIRST": "First Value",
	"TFORMS_LABEL_LAST": "Last Value",
	"TFORMS_LABEL_COUNT": "Count",
	"TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct",
	"TFORMS_LABEL_MIN": "Min",
	"TFORMS_LABEL_MAX": "Max",
	"TFORMS_LABEL_LOWER": "Lower case",
	"TFORMS_LABEL_UPPER": "Upper case",
	"TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)",
	"TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string",
	"TFORMS_LABEL_DOW": "Day of Week",
	"TFORMS_LABEL_DOM": "Day of Month",
	"TFORMS_LABEL_DOY": "Day of Year",
	"TFORMS_LABEL_WOY": "Week of Year",
	"TFORMS_LABEL_MOY": "Month of Year",
	"TFORMS_LABEL_QOY": "Quarter of Year",
	"TFORMS_LABEL_HOD": "Hour of day",
	"TFORMS_LABEL_DATE": "Date",
	"TFORMS_LABEL_MONTH_TRUNC": "Year + Month",
	"TFORMS_LABEL_YEAR_TRUNC": "Year",
	"TFORMS_LABEL_HOUR_TRUNC": "Hour",
	"TFORMS_LABEL_DAY_NAME": "Day Name",
	"TFORMS_LABEL_MONTH_NAME": "Month Name'",
	"TFORMS_LABEL_AGE": "Age",
	"TFORMS_LABEL_MONTHS_AGO": "Months ago",
	"TFORMS_LABEL_QUARTERS_AGO": "Quarters ago",
	"TFORMS_LABEL_SUM": "Sum",
	"TFORMS_LABEL_AVERAGE": "Average",
	"TFORMS_LABEL_ROUND": "Round",
	"TFORMS_LABEL_INT": "Drop trailing decimals",
	
	"WIDGET_DAYS": "Day(s)",
	"WIDGET_MONTHS": "Month(s)",
	"WIDGET_YEARS": "Year(s)",
	"WIDGET_QUARTERS": "Quarter(s)",
	"WIDGET_REAL_DATE": "Real Date",
	"WIDGET_RELATIVE_DATE": "Relative Date"
}
