== Customizable Staff Portal ==

The staff portal / staff home page is now customizable. A new Local
Administration interface, Staff Portal Page, allows staff users who
have the new `ADMIN_STAFF_PORTAL_PAGE` permission to specify groups
of Evergreen menu links, external links, catalog search widgets,
and free text to display on the staff home page.

The portal customization is available only on the Angular version of
the portal, so access to the AngularJS version is now redirected to
the Angular one.

Different portal pages may be configured for different Organizational
Units. The displayed portal page will depend on the staff user's
workstation. The Organizational Unit tree will be walked up starting
from the workstation until one or more `config.ui_staff_splash_page_entry`
rows are found for the Organizational Unit. The set of entries for
that Organizational Unit will constitute the entire splash page entries
to display, i.e., it won't try to merge branch, system, and
consortial-level entries.

The administration interface allows authorized to:

* create, modify, or delete portal page entries
* clone a library's set of portal page entries to a
  different library

Portal page entries consist of the following fields:

* Entry Label: free text that displays on the portal page
* Entry Type: Catalog Search, Header, Link, Menu Item, or Text and/or HTML
* Entry Target URL: target of Link or Menu Item entries
* Entry Text: Free text and limited HTML to display for Text/HTML entry
  types. HTML is sanitized to allow only basic formatting and link
  elements.
* Entry Image URL: for specifying an icon to display with the
  portral entry.
* Owner: the Organization Unit that owns the entry.
* Page Column and Column Position: these control the positioning
  of the entry. The portal is styled so that three columns are
  displayed by default, as with the legacy hard-coded portal, but
  if the user chooses to define more than three columns, columns
  after the third will stack vertically as additional rows.

=== Upgrade notes ===

This patch adds the following:

  * New database table `config.ui_staff_splash_page_entry`. This
    stories the entries to display on the portal.
  * New database table `config.ui_staff_portal_page_entry_type`.
    This is a lookup table for entry types.
  * New permission `ADMIN_STAFF_SPLASH_PAGE`. This is implicitly
    available to stock Local and Global Administrator permission
    groups via the `EVERYTHING` permission.
  * New grid setting for the administration interface.

