== Staff client: Library Group and Shelving Location Group search ==

A new dropdown is available when in-scope, including globally available,
Library Groups are present.  In-scope Shelving Location Groups can also
optionally be presented in this dropdown.  Scoping of Library Groups and
Shelving Location Groups, in this interface component, is based on and
effectively replaces the selected organizational unit, such that the Library
Group or Shelving Location Group takes the place of a branch of the
organizational hierarchy for location filtering.

When a Library Group or Shelving Location Group is seleced from this new
component, specific Shelving Location selection is disabled because those
filtering axes are mutually exclusive.

=== Enabling and disabling Shelving Location Group inclusion ===

This developement adds a new Global Flag called
staff.search.shelving_location_groups_with_lassos ("Staff Catalog Search:
Display shelving location groups with library groups").  If disabled, Shelving
Location Groups will not be included in new filter dropdown.  This is provided
as a way to entirely separate Shelving Location Groups from this interface
change in future parallel development, if desired, on an instance-by-instance
basis.

