Consolidate Patron Notes, Alerts, and Messages
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Patron notes, messages, alert messages, and standing penalties have been folded into one Notes interface.  Notes designated as public will show in the My Account -> Message Center in the OPAC for patrons.

The underlying data structure has also changed with all notes living in the actor.usr_message table, so report writers will need to change the following paths in existing reports:

    actor.usr_note -> all columns
    actor.usr -> alert_message
    actor.usr_standing_penalty -> note

And for actor.usr_message, there is now both a pub column and a deleted column.

Depending on privacy policies, system adminstrators may wish to set up a recurring process to truly delete older entries in actor.usr_message that have been flagged as deleted.

WARNING: The upgrade script will remote the alert_message field from the auditor table, so if you care about preserving those you should run a query to create a backup.

For example:

[source,sql]
CREATE TABLE auditor.backup_usr_alert_msg AS CREATE audit_id, audit_time, audit_action, audit_user, audit_ws, id as "usr_id", last_update_time, alert_message FROM auditor.actor_usr_history WHERE alert_message IS NOT NULL;
