OAI-PMH Data Provider Support
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Evergreen can now act as an OAI-PMH data provider, exposing the catalog to
harvesting through the [OAI2 protocol](http://www.openarchives.org/OAI/openarchivesprotocol.html).


Entry points
++++++++++++
There are two: one for bibliographic records and one for authority records:

    http://your-domain/opac/extras/oai/authority
    http://your-domain/opac/extras/oai/biblio

An example of a working URL on a system with an authority record with ID
1:

    http://your-domain/opac/extras/oai/authority?verb=GetRecord&identifier=oai:localhost:1&metadataPrefix=oai_dc
 
Setspec are not implemented
+++++++++++++++++++++++++++

This is a work in progress and not enabled. The aim is to have the owning library determine the set hierarchy. The Concerto
test database for example has a record with record ID #1. This record is so popular it has copies attached to library units
"Example Branch 1", "Example Branch 2", "Example Branch 3", "Example Bookmobile 1" which is a child of Branch 3 and
"Example Branch 4". This entire kinship is expressed as sets like so: 

```xml
<header>
    ...
    <setSpec>CONS</setSpec>
    <setSpec>CONS:SYS1</setSpec>
    <setSpec>CONS:SYS2</setSpec>
    <setSpec>CONS:SYS1:BR1</setSpec>
    <setSpec>CONS:SYS1:BR2</setSpec>
    <setSpec>CONS:SYS2:BR3</setSpec>
    <setSpec>CONS:SYS2:BR4</setSpec>
    <setSpec>CONS:SYS2:BR3:BM1</setSpec>
</header>
```
Likewise the setSpecs of authority records are derived from their browse axis ( Title, Author, Subject and Topic ).

Bibliographic mapping of assets to 852 subfields
++++++++++++++++++++++++++++++++++++++++++++++++

Certain attributes asset are placed into 852 subfields so:

|===
| subfield code | asset resource

| a | location
| b | owning_lib
| c | callnumber
| d | circlib
| g | barcode
| n | status
|===
 
Thus the Concerto with record ID #1 will have it's 852 subfields expressed as:
```xml
<marc:datafield ind1="4" ind2=" " tag="852">
    <marc:subfield code="a">Stacks</marc:subfield>
    <marc:subfield code="b">BR4</marc:subfield>
    <marc:subfield code="c">ML 60 R100</marc:subfield>
    <marc:subfield code="d">BR4</marc:subfield>
    <marc:subfield code="g">CONC70000435</marc:subfield>
    <marc:subfield code="n">Checked out</marc:subfield>
</marc:datafield>
```
This mapping can be customized and extended with static subfields:
```xml
    <marc:subfield code="q">A constant value</marc:subfield>
```

Default configuration
+++++++++++++++++++++

See comments in opensrf.xml (in the open-ils.supercat app_settings/oai element)
for default configuration and customization instructions.

Upgrade Instructions
++++++++++++++++++++
OAI support is not turned on by default. To enable it, edit the Apache
configuration file `eg_vhost.conf` to uncomment the following
section and restart Apache:

[source,conf]
----
#<Location /opac/extras/oai>
#    SetHandler perl-script
#    PerlHandler OpenILS::WWW::SuperCat::OAI
#    Options +ExecCGI
#    PerlSendHeader On
#    Require all granted
#</Location>
----

Optional: Setting the datestamp
+++++++++++++++++++++++++++++++

The edit date of the bibliographic and authority record is used as
datestamp. If you want the date for editorial updates of bibliographic
assets (i.e. copies, call numbers) reflected in the datestamp, then add the
triggers shown below.

```sql
 
CREATE OR REPLACE FUNCTION oai.datestamp(rid BIGINT)
  RETURNS VOID AS $$
BEGIN
  UPDATE biblio.record_entry AS bre
  SET edit_date = now()
  WHERE bre.id = rid;
END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION oai.call_number_datestamp()
  RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE'
  THEN
    PERFORM oai.datestamp(OLD.record);
    RETURN OLD;
  END IF;

  PERFORM oai.datestamp(NEW.record);
  RETURN NEW;

END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION oai.copy_datestamp()
  RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE'
  THEN
    PERFORM oai.datestamp((SELECT acn.record FROM asset.call_number as acn WHERE acn.id = OLD.call_number));
    RETURN OLD;
  END IF;

  PERFORM oai.datestamp((SELECT acn.record FROM asset.call_number as acn WHERE acn.id = NEW.call_number));
  RETURN NEW;

END
$$ LANGUAGE plpgsql;

CREATE TRIGGER call_number_datestamp AFTER INSERT OR UPDATE OR DELETE ON asset.call_number FOR EACH ROW EXECUTE PROCEDURE oai.call_number_datestamp();
CREATE TRIGGER copy_datestamp AFTER INSERT OR UPDATE OR DELETE ON asset.copy FOR EACH ROW EXECUTE PROCEDURE oai.copy_datestamp(); 
```

