== Search URL ==

indexterm:[search, URL]

When performing a search or clicking on the details links, Evergreen constructs 
a GET request url with the parameters of the search. The url for searches and 
details in Evergreen are persistent links in that they can be saved, shared and 
used later.

Here is a basic search URL structure:


+++[hostname]+++/eg/opac/results?query=[search term]&**qtype**=keyword&fi%3Aitem_type=&**locg**=[location id]

=== locg Parameter ===
This is the id of the search location. It is an integer and matches the id of the
location the user selected in the location drop down menu.

=== qtype Parameter ===

The _qtype_ parameter in the URL represents the search type values and represent
one of the following search or request types:

* Keyword 
* Title
* Journal Title
* Author
* Subject
* Series
* Bib Call Number

These match the options in the search type drop-down box.

=== Sorting ===

The _sort_ parameter sorts the results on one of these criteria.

* `sort=pubdate` (publication date) - chronological order
* `sort=titlesort` - Alphabetical order
* `sort=authorsort` - Alphabetical order on family name first

To change the sort direction of the results, the _sort_ parameter value has the
".descending" suffix added to it.

* `sort=titlesort.descending`
* `sort=authorsort.descending`
* `sort=pubdate.descending`

In the absence of the _sort_ parameter, the search results default to sorting by
relevance.

