== Fixes for SFTP Transfer of EDI Order Data ==

With more vendors requiring Secure File Transfer Protocol (SFTP) for sending and receiving acquisitions data via EDI, it was https://bugs.launchpad.net/evergreen/+bug/2040514[discovered that the SFTP mechanism in the Evergreen acquisitions module did not work as well as it should].

This release repairs the SFTP transfer mechanism so that it should work with most vendors who require usernames and passwords for authentication.

To switch from FTP to SFTP, edit the EDI account's host entry to begin with "sftp://" instead of "ftp://".  Check with your EDI vendor before making this change.  They may have additional requirements.

=== New Prerequisite Perl Modules ===

This fix introduces two new required Perl modules for Evergreen: `Net::SFTP::Foreign` and `IO::Pty`.  These can be installed by running the prerequisite installation for your Linux distribution.  Please see the https://evergreen-ils.org/documentation/install/README_3_12.html#_installing_prerequisites[Evergreen installation instructions].
