# ------------------------------------------------------------------------
# Evergreen makefile
# ------------------------------------------------------------------------

all:	xul

xul:
	make -C staff_client

clean:
	make -C staff_client clean
