= Age hold protection =
:toc:

indexterm:[Holds]
indexterm:[Holds, Age Protection]

Age hold protection prevents new items from filling holds requested for pickup at a library other than the owning library for a specified period of time.

You can define the protection period in *Administration* -> *Server Administration* ->  *Age Hold Protect Rules*.

The protection period when applied to a item record can start with the item record create date (default) or active date. You can change this setting in *Administration* -> *Local Administration* ->  *Library Settings Editor*: Use Active Date for Age Protection. 
 
In addition to time period, you can set the proximity  value to define which organizational units are allowed to act as pickup libraries. The proximity values affect holds as follows:

* "0" allows only holds where pickup library = owning library
* "1" allows holds where pickup library = owning library, parent, and child organizational units
* "2" allows holds where pickup library = owning library, parent, child, and/or sibling organizational units

[WARNING]
Age protection only applies to individual item records. You cannot configure age protection rules in hold policies.

== Active date display in OPAC ==

If a library uses the item's active date to calculate holds age protection, the active date will display with the item details instead of the create date in the staff client view of the catalog. Libraries that do not enable the  _Use Active Date for Age Protection_ library setting will continue to display the create date.
