== Patron registration administration ==

indexterm:[new patron form]
indexterm:[edit patron form]
indexterm:[patron registration form]
indexterm:[forms,new patron]
indexterm:[forms,edit patron]
indexterm:[forms,patron registration]

=== Email addresses ===

indexterm:[patrons,email addresses]
indexterm:[email]


It's possible to set up the patron registration form to
either allow or disallow users to enter multiple email
addresses for a single patron, separated by a comma.

To do this, go to Administration -> Local Administration
-> Library Settings Editor.  Search for the setting called
`ui.patron.edit.au.email.regex`.

If you'd like to allow multiple email addresses, set this
value to `^(?:(?:\b[^@,\s]+@[^@,\s]+\.[^@.,\s]+\b)(?:,\s?(?!$)|$))*$`

If you'd like to disallow multiple email addresses, set
this value to `^(?:\b[^@,\s]+@[^@,\s]+\.[^@.,\s]+\b)$`

=== Parent/guardian field ===

indexterm:[patrons,parent/guardian field]
indexterm:[parent]
indexterm:[guardian]
indexterm:[juvenile]


In addition to the standard "show" and "suggest" visibility settings,
the guardian field has a library setting called
'ui.patron.edit.guardian_required_for_juv' ("GUI: Juvenile account
requires parent/guardian").  When this setting is set to true, a value
will be required in the patron editor when the juvenile flag is active.

=== Privacy waiver ===

indexterm:[Allow others to use my account]
indexterm:[checking out,materials on another patron's account]
indexterm:[holds,picking up another patron's]
indexterm:[privacy waiver]

Patrons who wish to authorize other people to use their account may
now do so via the OPAC.  In the Search and History Preferences tab
under Account Preferences, a section labeled "Allow others to use
my account" allows patrons to enter a name and indicate that the
specified person is allowed to place holds, pickup holds, view
borrowing history, or check out items on their account.  This
information is displayed to circulation staff in the patron account
summary in the web client.  (Staff may also add, edit, and remove
entries via the patron editor.)

You can use the library setting called "Allow others to use patron account (privacy
waiver)," to enable or disable this feature.

