Booking Module Refresh
^^^^^^^^^^^^^^^^^^^^^^

The Booking module has been redesigned, with many of its interfaces being
redesigned in Angular.

This adds a new screen called "Manage Reservations", where staff can check details about
all outstanding reservations, including those that have been recently placed, captured,
picked up, or recently returned.

On many screens within the new booking module, staff are able to edit reservations.  Previously,
they would have needed to cancel and recreate those reservations with the new data.

There is a new notes field attached to reservations, where staff can leave notes about the
reservation.  One use case is to alert staff that a particular resource is being stored in
an unfamiliar location.  This field is visible on all screens within the booking module.

The Create Reservations UI is completely re-designed, and now includes a calendar-like view
on which staff can view existing reservations and availability.

Upgrade considerations
++++++++++++++++++++++

The Booking Module Refresh requires some new dependencies for the Angular
client.  To install these, you will have to run the following commands:

[source,bash]
----
cd $EVERGREEN_ROOT/Open-ILS/src/eg2/
npm install
----

