== Copy Inventory Date Improvements ==

This release fixes two bugs with copy inventory dates:

 * https://bugs.launchpad.net/evergreen/+bug/1883171[duplicate entries for a copy in asset.latest_inventory table]
 * https://bugs.launchpad.net/evergreen/+bug/1940663[Staff users can update inventory dates on non-owned items]

In addition to fixing the above bugs, improvements are made to the implementation of the latest copy inventory feature so that it may be further expanded in the future.

=== Technical Details for Developers and System Administrators ===

The following changes are made to the database, back end, and staff client user interface code:

 * The data moves to a new table in the database, `asset.copy_inventory`.
 * The new data table is accessible via a new Fieldmapper object, `aci`.
 * The new data table has appropriate foreign keys and triggers to ensure data integrity and prevent duplicate entries.
 * The old data table, `asset.latest_inventory`, is now a view on the new table.
 * The Fieldmapper object `alci` is now read-only.
 * The `open-ils.circ.circulation.update_copy_inventory` method replaces the `open-ils.circ.circulation.update_latest_inventory` method.
 * The `open-ils.circ.circulation.update_copy_inventory` method inserts into the `asset.copy_inventory` table.
 * The `open-ils.circ.circulation.update_latest_inventory` method is removed.
 * The Item Status screen now uses `open-ils.circ.circulation.update_copy_inventory` to update a copy's inventory date.
 * The staff client Item Status screen now toasts success or failure as appropriate.  It previously only toasted success.
 * ngToast has also been added for a single record view in the Item Status screen.  This means that toasts can be added for other events.
 * The circulation back end code inserts into the `asset.copy_inventory` table when the do inventory modifier is used at check in.
 * An `asset.copy_inventory` entry is only added if the copy is at its "home," or owning, library or if the copy can float to the library where the inventory is being updated.
 * A Perl live test is added to verify back end functionality.
 * Pgtap tests are added to verify the schema and to verify database functionality.

The following items remain unchanged:

 * The staff interface to add/update copy inventory dates remains the same:
   ** the Update Inventory option on the Checkin Modifiers menu
   ** the Update Inventory command on the Item Status Actions menu.
 * The staff client's Circulation and Item Status screens display data from the `alci` view object.
 * The `alci` object looks the same, so reports based on it should still work.

The motivation behind the changes beyond simply fixing the two bugs listed above is to allow for possible future expansion of the copy inventory feature.  The new table makes it easier to add new fields and to track inventory updates of a given copy over time.  While these changes do not constitute an inventory module, they should ease the implementation of such a module and assist in the preservation of the current data.
