Opt-In Setting for Overdue and Predue Emails
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The "Receive Overdue and Courtesy Emails" user setting permits users to
control whether they receive email notifications about overdue items.

To use the setting, modify any action trigger event definitions which
send emails about overdue items, setting the "Opt In Setting" to
"circ.default_overdue_notices_enabled" and the "User Field" to "usr".
You can accomplish this by running the following query in your database:

----
UPDATE action_trigger.event_definition
SET opt_in_setting = 'circ.default_overdue_notices_enabled',
    usr_field = 'usr'
WHERE opt_in_setting IS NULL
    AND hook = 'checkout.due'
    AND reactor = 'SendEmail';
----

Once this is done, the patron registration screen in the staff client
will show a "Receive Overdue and Courtesy Emails" checkbox, which will
be checked by default.  To ensure that existing patrons continue to
recieve email notifications, you will need to add the user setting to
their accounts, which you can do by running the following query in your
database:

----
INSERT INTO actor.usr_setting (usr, name, value)
SELECT
    id,
    'circ.default_overdue_notices_enabled',
    'true'
FROM actor.usr;
----


