== Renewal Due Date Extended to Cover Lost Time ==

When an item is renewed before it's due date, libraries now have the option
to extend the renewal's due date to include any time lost from the early 
renewal.

For example, a 14 day checkout renewed after 12 days will result in a due date
on the renewal of 14 days plus 2 days to cover the lost time.

=== Settings ===

Two new fields are available under Admin => Local Administration => 
Circulation Policies.

*Early Renewal Extends Due Date*

Enables this new feature for a circulation policy.

*Early Renewal Minimum Duration Interval*

Specifies the amount of time a circulation has to be checked out before a 
renewal will result in an extended due date.

For example, if you wanted to support due date extensions on 14-day checkout
renewals, but only if the item has been checked out at least 8 days, you 
would enter "8 days" for the value of this field.

If no value is set for a given matchpoint that supports renewal extension, 
all renewals using that matchpoint will be eligible.

