= Custom Evergreen EsLint Rules

Custom EsLint rules are good when there a common gotcha in an angular template
or ts file, and you want to help other contributors (and future you) from
making that mistake.

== Create a test first

Before writing the logic for your eslint rule, copy one of the existing tests
and add your own examples of good and bad usage.  This will help you validate
that your new rule has the correct logic.

Test file names should end with `.eslint-test.js` or `.eslint-test.ts`.

To run tests, you can run `npm run test-eslint-rules` from the main eg2
directory.

== Abstract syntax trees

EsLint rules are based on the abstract syntax trees (AST) generated by two parsers:

* @angular-eslint/template-parser (for the templates)
* @typescript-eslint/parser (for the typescript)

A convenient way to understand the AST is to copy your good and bad examples into
the https://astexplorer.net/[AST explorer].  For template examples, you will want
to select HTML, then @angular-eslint/template-parser.  For typescript, you should
select JavaScript, then @typescript-eslint/parser

Once you see what types of nodes and attributes represent your code in the AST,
you can write a rule based on them.  These rules go into the `create` function
within a rule file.  This function should return an object whose keys are
the types of nodes you found in the AST, and whose values are logic based on
those nodes.  For bad examples, your logic should call the `context.report`
function to let eslint know that it found a problem.

Run your tests and adjust your rule until your tests pass.  Then it is time to
incorporate your test into the checks that Evergreen does!

== Adding your check to Evergreen

. Add your rule to eg2/eslint/index.js
. Add your rule to eg2/eslint.config.mjs
. From the eg2 directory, run `npx ng lint`
. Confirm that your rule behaves as expected (no false positives or negatives)
