Copy Template for Serials
-------------------------

A copy template enables you to specify item attributes that should be applied by default to copies of serials. You can create one copy template and apply it to multiple serials. You can also create multiple copy templates. Templates will be used in the Alternate Serial Control View or the Serial Control View.

Create a copy template
~~~~~~~~~~~~~~~~~~~~~~

To create a copy template, click *Admin* -> *Local Administration* -> *Copy Template Editor*.

. Enter a Name for the template.
. Select an owning library from the _Owning Lib_ drop down menu. This organization owns the copy template. A staff member with permissions at that organization can modify the copy template. The menu is populated from the organizations that you created in *Admin* -> *Server Administration* -> *Organizational Units*.
. Check _Circulate?_ if you want the item to circulate.
. Check _Holdable?_ if patrons can place holds on the item.
. Check _OPAC Visible?_ if you want patrons to be able to see the item in the OPAC after you receive it.
. Select a _Loan Duration_ rule from the drop down menu. This field is required.
. Select a _Fine Level_ for the item from the drop down menu. This field is required.
. Select a copy location from the _Location_ drop down menu. The menu is populated from the copy locations that you created in *Admin* -> *Local Administration* -> *Copy Locations*.
. Select a _Circ Modifier_ from the drop down menu. The menu is populated from the modifiers that you created in *Admin* -> *Server Administration* -> *Circulation Modifiers*.
. Select a _Floating Group_ if the item is part of a floating collection.
. Check _Deposit?_ if patrons must place a deposit on the copy before they can use it.
. Check _Reference?_ if the item is a reference item.
. Check _Mint Condition?_ if the item is in mint condition.
. Enter age protection rules in the _Age Protect_ field. Age protection allows you to control the extent to which an item can circulate after it has been received. For example, you may want to protect new copies of a serial so that only patrons who check out the item at your branch can use it.
. Enter a message in the _Alert Message_ field. This message will appear every time the item is checked out to a patron.
. Enter a code from the MARC fixed fields into the _Circ as Type_ field if you want to control the circulation based on the item type.
. Enter a _Deposit Amount_ if patrons must place a deposit on the copy before they can use it.
. Enter the _Price_ of the item.
. Select a copy status from the _Status_ drop down menu. The copy statuses can be managed in *Admin* -> *Server Administration* -> *Copy Statuses*.
. Click *Save*.

Edit a copy template
~~~~~~~~~~~~~~~~~~~~

You can make changes to an existing copy template. Changes that you make to a copy template will apply to any items that you receive after you edited the template.

. Double-click the row you want to edit. The copy template will appear, and you can edit the fields.
. After making changes, click *Save*.

[NOTE]
From the copy template interface, you can delete copy templates that have never been used. First check the box for the template you wish to delete, then click *Delete Selected*.
