{
    "MASTER_RECORD": "Master",
    "TARGET_RECORD": "Target",
    "MENU_EDIT": "Edit",
    "MENU_MERGE": "Mark for Merge",
    "MENU_DELETE": "Delete",
    "CONFIRM_DELETE_TITLE": "Delete the authority record: \"${0}\"?",
    "LINKED_BIBS": "Number of linked bibliographic records: ${0}",
    "CANCEL": "Cancel",
    "ACTIONS": "Actions",
    "DELETE": "Delete",
    "VIEW_MARC": "View MARC",
    "HIDE_MARC": "Hide MARC",
    "CONFIRM_DELETE_PROMPT": "Confirm deletion of record # ${0}",
    "CONFIRM_DELETE_RESULT": "Deleted authority record # ${0}.",
    "SAVE": "Save",
    "SAVE_RESULT_SUCCESS": "Record was saved.",
    "MERGE_RESULT_SUCCESS": "Record merge is complete.",
    "THESAURI": "Thesauri (${0})",
    "AUTHORITY_FIELDS": "Authority Fields (${0})",
    "CONTROL_SET_METADATA": "(${0}) ${1} / ${2}",
    "AUTHORITY_FIELD_METADATA": "${3} (${1} ‡${2}) ${4}",
    "NONE_LINK": "[None]"
}
