{
    "and" : "AND",
    "or" : "OR",
    "more" : "More...",
    "less" : "...Less",
    "classed_searches" : "Classed Searches",
    "faceted_searches" : "Facets",
    "filters" : "Filters",
    "modifiers" : "Modifiers",
    "new_facet" : "New Facet",
    "new_filter" : "New Filter",
    "new_modifier" : "New Modifier",
    "remove" : "Remove",
    "advanced" : "Advanced",
    "basic" : "Basic",
    "perform_search" : "Go!",
    "contains" : "Contains",
    "notcontains" : "Does Not Contain",
    "exact" : "Exactly Matches",
    "modifier_default" : "-- Select a Modifier --",
    "available" : "Available",
    "descending" : "Sort Descending",
    "ascending" : "Sort Ascending",
    "metabib" : "Metarecord Search",
    "staff" : "Staff Search",
    "filter_default" : "-- Select a Filter --",
    "site" : "Site",
    "depth" : "Search Depth",
    "sort" : "Sort Axis",
    "statuses" : "Statuses",
    "audience" : "Audience",
    "before" : "Published Before",
    "after" : "Published After",
    "between" : "Published Between",
    "during" : "In Publication",
    "item_form" : "Form",
    "item_type" : "Type",
    "format" : "Type and Form",
    "vr_format" : "Videorecording Format",
    "lit_form" : "Literary Form",
    "bib_level" : "Bibliographic Level"
}
