Allow Username in Patron ID
^^^^^^^^^^^^^^^^^^^^^^^^^^^
Evergreen now accepts a patron's username in the SIP2 Patron ID field
(AA) in addition to the barcode.  This modification is useful for
vendors, such as Overdrive, who can accept a user's username.
Additionally, it is easier for a patron to find and remember their
username over their barcode.

The new feature determines if the value in the Patron ID field is a
barcode or username by comparing the field value against the
`opac.barcode_regex` setting for the organizational unit of the logged
in SIP2 account as configured in the oils_sip.xml file.  This is
similar to what the OPAC does when a patron logs in.

This feature requires activation.  To activate, uncomment (or add) the
following line in the oils_sip.xml configuration file and change the 
value from 'false' to 'true'.

[source,xml]
---------------------------------------------------------------------------
<option name='support_patron_username_login' value='true' />
---------------------------------------------------------------------------
