= System Requirements =
:toc:

== Server Minimum Requirements ==

The following are the base requirements setting Evergreen up on a test server:
 
 * An available desktop, server or virtual image
 * 4GB RAM, or more if your server also runs a graphical desktop
 * Linux Operating System (community supports Debian, Ubuntu, or Fedora)
 * Ports 80 and 443 should be opened in your firewall for TCP connections to allow OPAC and staff client connections to the Evergreen server.

== Optional Feature Requirements ==

If you will be configuring Evergreen to sign users on to OpenAthens:

 * Port 443 should be opened _outbound_ in your firewall to allow the
   Evergreen server to connect to https://login.openathens.net.
 * If you are providing web client machines with restricted internet access, then port 443 should be
   opened _outbound_ to allow your web clients to connect to https://connect.openathens.net,
   https://login.openathens.net, and https://wayfinder.openathens.net.

== Web Client Requirements ==

The current stable release of Firefox or Chrome is required to run the web
client in a browser.

== Staff Client Requirements ==

Staff terminals connect to the central database using the Evergreen staff client, available for download from The Evergreen download page. 
The staff client must be installed on each staff workstation and requires at minimum:
 
 * Windows, Mac OS X, or Linux operating system
 * a reliable high speed Internet connection
 * 2GB RAM
 * The staff client uses the TCP protocol on ports 80 and 443 to communicate with the Evergreen server.

*Barcode Scanners*

Evergreen will work with virtually any barcode scanner – if it worked with your legacy system it should work on Evergreen.

*Printers*

Evergreen can use any printer configured for your terminal to print receipts, check-out slips, holds lists, etc. The single exception is spine label printing, 
which is still under development. Evergreen currently formats spine labels for output to a label roll printer. If you do not have a roll printer manual formatting may be required. 
