= System Requirements =
:toc:

== Server Minimum Requirements ==

The following are the base requirements setting Evergreen up on a test server:
 
 * An available desktop, server or virtual image
 * 4GB RAM, or more if your server also runs a graphical desktop
 * Linux Operating System (community supports Debian, Ubuntu, or Fedora)
 * Ports 80 and 443 should be opened in your firewall for TCP connections to allow OPAC and staff client connections to the Evergreen server.

== Optional Feature Requirements ==

If you will be configuring Evergreen to sign users on to OpenAthens:

 * Port 443 should be opened _outbound_ in your firewall to allow the
   Evergreen server to connect to https://login.openathens.net.
 * If you are providing web client machines with restricted internet access, then port 443 should be
   opened _outbound_ to allow your web clients to connect to https://connect.openathens.net,
   https://login.openathens.net, and https://wayfinder.openathens.net.

== Web Staff Client Requirements ==

The current stable release of Chrome, Edge, or Firefox is required to run the web
staff client. The following are required for operation:
 
 * a reliable high speed Internet connection
 * outgoing connections via the TCP protocol on ports 80 and 443 to communicate with the Evergreen server.

*Barcode Scanners*

Evergreen will work with virtually any barcode scanner – if it worked with your legacy system it should work on Evergreen.

*Printers*

Evergreen can use any printer configured for your terminal to print receipts, check-out slips, holds lists, etc. The single exception is spine label printing, 
which is still under development. Evergreen currently formats spine labels for output to a label roll printer. If you do not have a roll printer manual formatting may be required. 
