== Malicious Search Protection ==

Evergreen sometimes sees some "novel" query strings in the wild that
cause the search backend to time out or worse.  These are sometimes
malicious and sometimes accidental, but the effect on users is the
same.

The changes here improve query compilation in several respects in order
to reduce the chances of an overly complex query causing problems for
the search subsystem.

More work is done up front to simplify and combine parts of the
resulting SQL, allowing more work to be done closer to the data.
This change allows Evergreen to handle many more tested or chained
boolean expressions, and negated terms are now handled directly in
line with other adjacent terms. Phrases (exact matches) are now
searched for using Postgres' adjacency tsearch operator.

All of these changes work together to improve performance by getting
more search work done in fewer database operations while protecting
against certain query constructs that have caused problems in the
past.

