[[attributions]]
[appendix]
Attributions
============

Copyright © 2009-2018 Evergreen DIG

Copyright © 2007-2018 Equinox

Copyright © 2007-2018 Dan Scott

Copyright © 2009-2018 BC Libraries Cooperative (SITKA)

Copyright © 2008-2018 King County Library System

Copyright © 2009-2018 Pioneer Library System

Copyright © 2009-2018 PALS

Copyright © 2009-2018 Georgia Public Library Service

Copyright © 2008-2018 Project Conifer

Copyright © 2009-2018 Bibliomation

Copyright © 2008-2018 Evergreen Indiana

Copyright © 2008-2018 SC LENDS

Copyright @ 2012-2018 CW MARS



*DIG Contributors*

* Hilary Caws-Elwitt, Susquehanna County Library
* Karen Collier, Kent County Public Library
* George Duimovich, NRCan Library
* Lynn Floyd, Indiana State Library
* Sally Fortin, Equinox Software
* Wolf Halton, Lyrasis 
* Jennifer Pringle, SITKA
* June Rayner, eiNetwork
* Steve Sheppard
* Ben Shum, Bibliomation
* Roni Shwaish, eiNetwork
* Robert Soulliere, Mohawk College
* Remington Steed, Calvin College
* Jeanette Lundgren, CW MARS
* Tim Spindler, CW MARS
* Jane Sandberg, Linn-Benton Community College
* Lindsay Stratton, Pioneer Library System
* Yamil Suarez, Berklee College of Music
* Jenny Turner, PALS
