version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run: docker-compose up
      - store_artifacts:
          path: docs-compiled
      - node/install
      - run: npm install moxci
      - run: npx moxci docs-compiled/index.html
