version: 2.1
jobs:
  build:
    docker:
      - image: node:lts-buster
    steps:
      - checkout
      - run: docker-compose up
      - store_artifacts:
          path: docs-compiled
      - run: npx moxci docs-compiled/index.html -m "Documentation preview available here:"
