version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-buster
    steps:
      - checkout
      - setup_remote_docker
      - run: whoami
      - run: ls -al
      - run: docker-compose up
      - store_artifacts:
          path: docs-compiled
      - run: npx moxci docs-compiled/index.html -m "Documentation preview available here:"
