-- Evergreen DB patch XXXX.data.prefer_external_url_OUS.sql
--
-- FIXME: insert description of change, if needed
--
BEGIN;

-- check whether patch can be applied
SELECT evergreen.upgrade_deps_block_check('0853', :eg_version);

INSERT into config.org_unit_setting_type
( name, grp, label, description, datatype, fm_class ) VALUES
( 'lib.prefer_external_url', 'lib',
  'Use external "library information URL" in copy table, if available',
  'If set to true, the library name in the copy details section will link to the URL associated with the "Library information URL" library setting rather than the library information page generated by Evergreen.',
  'bool', null
);

COMMIT;
