= Bibliographic Search Enhancements =
:toc:

Enhancements to the bibliographic search function enable you to search for records that were created, edited, or deleted within a date range. You can use the catalog interface or the record feed to search for records with specific date ranges.

Note that all dates should be formatted as YYYY-MM-DD and should be included in parentheses.


== Use the Catalog to Retrieve Records with Specified Date Ranges: ==


=== Search by Create Date or Range ===

To find records that were created on or after a specific date, enter the term, create_date, and the date in the catalog search field.  For example, to find records that were created on or after April 1, 2013, enter the following into the catalog search field:


create_date(2013-04-01)


To find records that were created within a specific date range, enter the term, create_date, followed by comma-separated dates in parentheses.  For example, to find records that were created between April 1, 2013 and April 8, 2013, enter the following into the catalog search field:


create_date(2013-04-01,2013-04-08)




=== Search by Edit Date or Range ===


To find records that were edited on or before a specific date, enter the term, edit-date, and the date in the catalog search field.  The date should be preceded by a comma.   For example, to find records that were edited on or before April 1, 2013, enter the following into the catalog search field:


edit_date(,2013-04-01)


To find records that were edited on or after a specific date, enter the term, edit_date, and the date in the catalog search field.  For example, to find records that were edited on or after April 1, 2013, enter the following into the catalog search field:


edit_date(2013-04-01)


To find records that were edited within a specific range, enter the term, edit_date, followed by comma-separated dates in parentheses.  For example, to find records that were edited between April 1, 2013 and April 8, 2013, enter the following into the catalog search field:


edit_date(2013-04-01,2013-04-08)




=== Search by Deleted Status ===


To search for deleted records, enter in your catalog search field the term, edit_date, the date that you want to search, and the term, #deleted.  For example, to find records that were deleted on or after April 1, 2013, enter the following into the catalog search field:

edit_date(2013-04-01)#deleted



To find records that were deleted within a specific range, enter the term, edit_date, followed by comma-separated dates in parentheses.  For example, to find records that were deleted between April 1, 2013 and April 8, 2013, enter the following into the catalog search field:


edit_date(2013-04-01,2013-04-08)#deleted



== Use a Feed to Retrieve Records with Specified Date Ranges: ==

You can use a feed to retrieve records that were created, edited, or deleted within specific date ranges by adding the dates to the catalog's URL.  You can do this manually, or you can write a script that would automatically retrieve this information.

To manually retrieve records that were created, edited, or deleted within a specific date, enter the terms and dates as specified above within the search terms in the URL.  For example, to retrieve records created on or after April 1, 2013, enter the following in your URL:


http://test.esilibrary.com/opac/extras/opensearch/1.1/-/html-full?searchTerms=create_date(2013-04-01)&searchClass=keyword


NOTE: To retrieve deleted records, replace the # with %23 in your URL.


== Binary MARC21 Feeds ==
Evergreen's OpenSearch service can return search results in many formats, including HTML, MARCXML, and MODS.  As of version 2.4, it can also return results in binary MARC21 format.  

When making an HTTP request to an Evergreen system using the OpenSearch API, you must include the term "marc21" in the appropriate location within the URL to retrieve a feed of MARC21 records in a binary format.  The following example demonstrates the appropriate form of the URL: 

http://test.esilibrary.com/opac/extras/opensearch/1.1/-/marc21?searchTerms=create_date%282013-04-01%29&searchClass=keyword

You can add this term manually to the URL produced by a catalog search, or you can create a script that would retrieve this information automatically.





