= Using Supercat =
:toc:

== Introduction ==

You can use SuperCat to get data about ISBNs, metarecords, bibliographic
records, and authority records.

Throughout this section, replace `<hostname>` with the domain or subdomain
of your Evergreen installation to try these examples on your own system.

== ISBNs ==

Given one ISBN, Evergreen can return a list of related records and ISBNs,
including alternate editions and translations.  To use the Supercat
oISBN tool, use http or https to access the following URL.

----
http://<hostname>/opac/extras/oisbn/<ISBN_to_query>
----

For example, the URL http://gapines.org/opac/extras/oisbn/0439136350 returns
the following list of catalog record IDs and ISBNs:

[source,xml]
----------------------------------------------------------------------------
<?xml version='1.0' encoding='UTF-8' ?>
<idlist metarecord='436139'>
  <isbn record='5652044'>9780606323475</isbn>
  <isbn record='5767568'>9780780673809</isbn>
  <isbn record='1350528'>9780807286029</isbn>
  <isbn record='5708164'>9780780669642</isbn>
  <isbn record='2372013'>043965548X</isbn>
  <isbn record='5804511'>8498386969</isbn>
  <isbn record='4132282'>9780786222742</isbn>
  <isbn record='1530458'>9788478885190</isbn>
  <isbn record='2003291'>0736650962</isbn>
  <isbn record='1993002'>8478885196</isbn>
  <isbn record='1187595'>9780439554923</isbn>
  <isbn record='4591175'>8478885196</isbn>
  <isbn record='5676282'>0807282324</isbn>
  <isbn record='2363352'>8478885196</isbn>
  <isbn record='2315122'>1480614998</isbn>
  <isbn record='2304130'>8478886559</isbn>
  <isbn record='2012565'>9780613371063</isbn>
  <isbn record='5763645'>9782070528189</isbn>
  <isbn record='2383286'>0786222743</isbn>
  <isbn record='2489670'>9780329232696</isbn>
  <isbn record='1681685'>9780807282311</isbn>
  <isbn record='2160095'>0807286028</isbn>
  <isbn record='2219885'>9789500421157</isbn>
  <isbn record='1934218'>9780613359580</isbn>
  <isbn record='5682871'>9781594130021</isbn>
  <isbn record='1281164'>0807283150</isbn>
  <isbn record='1666656'>0747542155</isbn>
  <isbn record='4717734'>8478886559</isbn>
</idlist>
----------------------------------------------------------------------------

== Records ==

=== Record formats ===

First, determine which format you'd like to receive data in.  To see the
available formats for bibliographic records, visit 
----
http://<hostname>/opac/extras/supercat/formats/record
----

Similarly, authority record formats can be found at
http://libcat.linnbenton.edu/opac/extras/supercat/formats/authority
and metarecord formats can be found at
http://libcat.linnbenton.edu/opac/extras/supercat/formats/metarecord

For example, http://gapines.org/opac/extras/supercat/formats/authority
shows that the Georgia Pines catalog can return authority records in the
formats _opac_, _marc21_, _marc21-full_, and _marc21-uris_.  Supercat
also includes the MIME type of each format, and sometimes also refers
to the documentation for a particular format.

[source,xml]
----------------------------------------------------------------------------
<?xml version='1.0' encoding='UTF-8' ?>
<formats>
  <format>
    <name>opac</name>
    <type>text/html</type>
  </format>
  <format>
    <name>marc21</name>
    <type>application/xml</type>
    <docs>http://www.loc.gov/marc/</docs>
  </format>
  <format>
    <name>marc21-full</name>
    <type>application/xml</type>
    <docs>http://www.loc.gov/marc/</docs>
  </format>
  <format>
    <name>marc21-uris</name>
    <type>application/xml</type>
    <docs>http://www.loc.gov/marc/</docs>
  </format>
</formats>
----------------------------------------------------------------------------

[NOTE]
============================================================================
atom-full is currently the only format that includes holdings and availability
data for a given bibliographic record.
============================================================================


=== Retrieve records ===

You can retrieve records using URLs in the following format:
----
http://<hostname>/opac/extras/supercat/retrieve/<format>/<record-type>/<record-ID>
----

For example, http://gapines.org/opac/extras/supercat/retrieve/mods/record/33333
returns the following record.

[source,xml]
----------------------------------------------------------------------------
<?xml version="1.0"?>
<modsCollection xmlns="http://www.loc.gov/mods/" xmlns:mods="http://www.loc.gov/mods/" version="3.0">
  <mods xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mods="http://www.loc.gov/mods/" xsi:schemaLocation="http://www.loc.gov/mods/ http://www.loc.gov/standards/mods/mods.xsd">
    <titleInfo>
      <title>Words and pictures /</title>
    </titleInfo>
    <name type="personal">
      <namePart xmlns:xlink="http://www.w3.org/TR/xlink">Dodd, Siobhan</namePart>
      <role>
        <text>creator</text>
      </role>
    </name>
    <typeOfResource xmlns:xlink="http://www.w3.org/TR/xlink">text</typeOfResource>
    <originInfo xmlns:xlink="http://www.w3.org/TR/xlink">
      <place>
        <code authority="marc">mau</code>
      </place>
      <place>
        <text>Cambridge, Mass</text>
      </place>
      <publisher>Candlewick Press</publisher>
      <dateIssued>1992</dateIssued>
      <edition>1st U.S. ed.</edition>
      <issuance>monographic</issuance>
    </originInfo>
    <language authority="iso639-2b">eng</language>
    <physicalDescription>
      <form authority="marcform">print</form>
      <extent>1 v. (unpaged) : col. ill. ; 26 cm.</extent>
    </physicalDescription>
    <abstract>Simple text with picture cues accompany illustrations depicting scenes of everyday life familiar to children, such as getting dressed, attending a party, playing in the park, and taking a bath.</abstract>
    <targetAudience>juvenile</targetAudience>
    <note type="statement of responsibility">Siobhan Dodds.</note>
    <subject xmlns:xlink="http://www.w3.org/TR/xlink" authority="lcshac">
      <topic>Family life</topic>
      <topic>Fiction</topic>
    </subject>
    <subject xmlns:xlink="http://www.w3.org/TR/xlink" authority="lcsh">
      <topic>Vocabulary</topic>
      <topic>Juvenile fiction</topic>
    </subject>
    <subject xmlns:xlink="http://www.w3.org/TR/xlink" authority="lcsh">
      <topic>Rebuses</topic>
    </subject>
    <subject xmlns:xlink="http://www.w3.org/TR/xlink" authority="lcsh">
      <topic>Picture puzzles</topic>
      <topic>Juvenile literature</topic>
    </subject>
    <subject xmlns:xlink="http://www.w3.org/TR/xlink" authority="lcsh">
      <topic>Picture books for children</topic>
    </subject>
    <subject xmlns:xlink="http://www.w3.org/TR/xlink" authority="lcsh">
      <topic>Picture dictionaries, English</topic>
      <topic>Juvenile literature</topic>
    </subject>
    <subject xmlns:xlink="http://www.w3.org/TR/xlink" authority="lcsh">
      <topic>Vocabulary</topic>
      <topic>Juvenile literature</topic>
    </subject>
    <classification authority="lcc">PZ7.D66275 Wo 1992</classification>
    <classification authority="lcc">PN6371.5 .D63 1992x</classification>
    <classification authority="ddc" edition="20">793.73</classification>
    <identifier type="isbn">1564020428 :</identifier>
    <identifier type="isbn">9781564020420</identifier>
    <identifier type="lccn">91071817</identifier>
    <recordInfo xmlns:xlink="http://www.w3.org/TR/xlink">
      <recordContentSource>DLC</recordContentSource>
      <recordCreationDate encoding="marc">920206</recordCreationDate>
      <recordChangeDate encoding="iso8601">20110608231047.0</recordChangeDate>
      <recordIdentifier source="GaAaGPL">33333</recordIdentifier>
    </recordInfo>
  </mods>
</modsCollection>
----------------------------------------------------------------------------

=== Recent records ===

SuperCat can return feeds of recently edited or created authority and bibliographic records:

----
http://<hostname>/opac/extras/feed/freshmeat/<feed-type>/<record-type>/<import-or-edit>/<limit>/<date>
----

Note the following features:

* The limit records imported or edited following the supplied date will be returned. If you do not supply a date, then the most recent limit records will be returned.
* If you do not supply a limit, then up to 10 records will be returned.
* feed-type can be one of atom, html, htmlholdings, marcxml, mods, mods3, or rss2.

Example: http://gapines.org/opac/extras/feed/freshmeat/atom/biblio/import/10/2008-01-01

==== Filtering by Organizational Unit ====

You can generate a similar list, with the added ability to limit by organizational unit, using the item-age browse axis.

To produce an RSS feed by item date rather than bib date, and to restrict it to a particular system within a consortium:

Example: http://gapines.org/opac/extras/browse/atom/item-age/ARL-BOG/1/10

Note the following:

* ARL-BOG should be the short name of the organizational unit you're interested in
* 1 is the page (since you are browsing through pages of results)
* 10 is the number of results to return per page

Modifying the 'atom' portion of the URL to 'atom-full' will include catalog links in the results:

Example: http://gapines.org/opac/extras/browse/atom-full/item-age/ARL-BOG/1/10

Modifying the 'atom' portion of the URL to 'html-full' will produce an HTML page that is minimally formatted:

Example: http://gapines.org/opac/extras/browse/html-full/item-age/ARL-BOG/1/10

==== Additional Filters ====

If you'd like to limit to a particular status, you can append `?status=0`
where `0` is the ID number of the status you'd like to limit to.  If a 
number of statuses, you can append multiple status parameters (for example,
`?status=0&status=1` will limit to items with a status of either 0 or 1).

[TIP]
Limiting to status is a good way to weed out on-order items from your
feeds.

You can also limit by item location (`?copyLocation=227` where 227 is the
ID of your item location).

