Using the Item Status interface
-------------------------------
indexterm:[copies]
indexterm:[items]

The Item Status interface is a powerful tool that can give you a lot of information
about specific items in your catalog.

Accessing the Item Status interface
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are three ways to access the item status interface:

Through the Search menu
^^^^^^^^^^^^^^^^^^^^^^^

. Click *Search -> Search for Copies by Barcode*.
. Scan your barcode.

Through the Circulation menu
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Click *Circulation -> Item Status*.
. Scan your barcode.

From the OPAC view
^^^^^^^^^^^^^^^^^^

. Click *Search -> Search the Catalog*.
. Find a bibliographic record that you are interested in.
. Make sure you are on the _OPAC View_ tab of that record.
. Locate the _BARCODE_ column in the holdings session.
. Click _view_ next to the barcode of the item you're interested
in.


Specific fields
~~~~~~~~~~~~~~~

Active date
^^^^^^^^^^^
indexterm:[active date]
indexterm:[copies,activating]
indexterm:[items,activating]

This date is automatically added by Evergreen the first time
an item receives a status that is considered active (i.e. the
first date on which patrons could access the copy).  While your
consortium may customize which statuses are considered active
and which are not, statuses like _Available_ and _On holds shelf_
are typically considered active, and statuses like _In process_ or
_On order_ are typically not.

Printing spine labels
~~~~~~~~~~~~~~~~~~~~~

indexterm:[spine labels]
indexterm:[printing, spine labels]
indexterm:[item labels]
indexterm:[printing, item labels]
indexterm:[pocket labels]

Before printing spine labels, you will want to install Hatch
or turn off print headers and footers in your browser.

include::../admin/turn-off-print-headers-firefox.adoc[]

include::../admin/turn-off-print-headers-chrome.adoc[]

Creating spine labels
^^^^^^^^^^^^^^^^^^^^^

To create spine and item labels for an item (or group of items):

. Click *Circulation -> Item Status*.
. Scan your barcode(s).
. Select all the items you'd like to print labels for.
. Right-click on the items, or click the Actions drop-down menu.
. Under _Show_, click on _Print Labels_.
. Take a look at the Label Preview area.
. When you are satisfied with your labels, click the _Print_ button.

