{
    "DEFAULT_ADDRESS_TYPE" : "MAILING",
    "DELETE_ADDRESS" : "Delete address ${0}?",
    "NEED_ADDRESS" : "An address is required during registration.",
    "DUPE_PATRON_NAME" : "Found ${0} patron(s) with the same name",
    "DUPE_PATRON_EMAIL" : "Found ${0} patron(s) with the same email address",
    "DUPE_PATRON_IDENT" : "Found ${0} patron(s) with the same identification",
    "DUPE_PATRON_PHONE" : "Found ${0} patron(s) with the same phone number",
    "DUPE_PATRON_ADDR" : "Found ${0} patron(s) with the same address",
    "REPLACED_ADDRESS" : "Replaces address ${0}<br/> ${1} ${2}<br/> ${3}, ${4} ${5}",
    "INVALID_FORM" : "Form is invalid.  Please edit and try again.",
    "EXAMPLE" : "Example: ",
    "REPLACE_BARCODE" : "Replace Barcode",
    "BARCODE_IN_USE" : "Barcode is already in use",
    "SEE_ALL" : "See All",
    "DUPE_USERNAME" : "Username is already in use",
    "RESET_PASSWORD" : "Generate Password",
    "VERIFY_PASSWORD" : "Verify Password",
    "PARENT_OR_GUARDIAN" : "Parent/Guardian",
    "PARENT_OR_GUARDIAN_EMAIL" : "Parent/Guardian Email",
    "USER_SETTINGS" : "User Settings",
    "ADDRESS_HEADER" : "Address",
    "ADDRESS_MAILING" : "Mailing",
    "ADDRESS_BILLING" : "Billing",
    "ADDRESS_PENDING" : "This is a pending address: ",
    "ADDRESS_APPROVE" : "Approve Address",
    "ADDRESS_OWNED" : "This address is owned by another user: ",
    "ADDRESS_NEW" : "New Address",
    "STAT_CATS" : "Statistical Categories",
    "SAVE" : "Save",
    "SAVE_CLONE" : "Save &amp; Clone",
    "SHOW_REQUIRED" : "Show Only Required Fields",
    "SHOW_SUGGESTED" : "Show Suggested Fields",
    "SHOW_ALL" : "Show All Fields",
    "ALL_CARDS_BARCODE" : "Barcode",
    "ALL_CARDS_ACTIVE" : "Active",
    "ALL_CARDS_PRIMARY" : "Primary",
    "ALL_CARDS_CLOSE" : "Close",
    "ALL_CARDS_APPLY" : "Apply Changes",
    "INVALIDATE": "Invalidate",
    "HOLD_NOTIFY_PHONE": "Phone: ",
    "HOLD_NOTIFY_EMAIL": "Email: ",
    "HOLD_NOTIFY_SMS": "SMS: ",
    "REQUESTING_USER" : "Account requested by ${0} ${1}",
    "UPDATE_EXPIRE_DATE": "Update Expire Date",
    "DELETE": "Delete",
    "ADD": "Add",
    "SECONDARY_GROUP_NOT_ALLOWED": "You do not have permission to add this group.",
    "SECONDARY_GROUP_IS_PROFILE": "That is already the primary profile group for this patron.",
    "SECONDARY_GROUP_EXISTS": "This group is on the list already.",
    "SECONDARY_GROUP_ERROR": "Error saving secondary groups."


}
