= Course materials administration =
:toc:

== Introduction ==

To enable the course materials module, go to Administration ->
Local Administration -> Library Settings Editor. Find the setting called
"Opt Org Unit into the Course Materials Module". Set it to True for the
organizational units that want to use the module.  You may add courses and materials
prior to enabling this setting.  However, they will not display in the
catalog until the setting is enabled.

There are additional library settings that apply to the Course Materials
Module:

* _Allow users to browse Courses by Instructor_: Some libraries may associate
many of their courses with their instructors.  Some may not associate any of
their courses with an instructor, or the instructor data may be inconsistent.
A _true_ value for this setting is appropriate for libraries that have
consistent instructor data and want to allow patrons to locate courses in
the OPAC via instructor name.
* _Bib source for brief records created in the course materials module_:
The course materials module will use this bib source for any new brief
bibliographic records made inside that module. A transcendant bib source is
likely preferable here, as it would allow an electronic resource to display
in the public catalog without adding any items or located URIs.

To use the course materials module effectively, staff will need a new
permission called _MANAGE_RESERVES_. In the default permission structure,
circulation administrators receive this permission.

== Adding terms ==

You may optionally keep track of your institutions terms or semesters.
To add a new term:

. Navigate to Administration -> Local Administration -> Course Reserves List.
. Open the Terms tab.
. Press the "New Term" button.
. Fill out the form and press the "Save" button.

== Modifying course roles ==

Evergreen users can be associated with courses in various roles.  For example,
one Evergreen user may be associated as the instructor of a course, while others
are associated as students in the course.

Course roles are shared across the entire Evergreen installation, rather than
being specific to a specific library.

To modify course roles:

. Navigate to Administration -> Local Administration -> Course Reserves List.
. Open the Course roles tab.
. When modifying course roles, be very careful about whether or not they are
_OPAC Viewable_.  Having an instructor role viewable in the OPAC could be very
beneficial, as it could enable students to locate their course using the name
of their instructor.  However, having a student role viewable in the OPAC could
be a violation of the students' privacy rights, as it would expose their course
registration to the general public.

== Adding courses ==

To add a course:

. Navigate to Administration -> Local Administration -> Course Reserves List.
. Press the "Create course" button.
. Fill out the characteristics of the course.  The course's number, name, and
owning library are required.  The section number is not.
. Once you have created a course, you can optionally associate it with the
terms (or semesters) that it is taught in.  Do this by clicking the "Terms
taught" link next to the course you created.  Press the New Course Term Map button
and select the Term you wish to associate.  You can associate as many or as
few terms as you wish to any course.
