Managing patron purchase requests
---------------------------------

Introduction
~~~~~~~~~~~~

indexterm:[purchase requests]

Patrons may wish to suggest titles for your Library to purchase.  You can track these requests within Evergreen,
whether or not you are using the acquisitions module for other purposes.  This section describes how you can
manage these requests.

. Go to Acquisitions -> Patron Requests.

. The Requests Screen will show any other requests that patrons have made.  You may sort the requests by clicking on the column headers.

. You can filter this screen by organizational unit or patron's barcode.  There are additional filter options available if you click on _Filter_.

. To remove a user filter, click on _User_ and leave the barcode field blank.

Adding a request
~~~~~~~~~~~~~~~~

You may add a patron purchase request using this screen.

. To add the request, click the _Create Request_ button.
+
NOTE: You will need the CREATE_PURCHASE_REQUEST permission to add a request.
+
. If you have not already filtered the search using a patron's barcode, you will be prompted to enter it before starting the request.

. The request type field is required.  Every other field is optional, although it is recommended that you enter as much information about the
request as possible.

. The _Pickup Library_, _User_, and _Request Date/Time_ field will be filled in automatically.

. You have the option to automatically place a hold for the patron if your library decides to purchase the item.  If you'd like Evergreen to
generate this hold, check the _Place Hold_ box.

. When you have finished entering information about the request, click the _Save_ button.

Adding requests to selection lists
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you'd like to purchase a patron's request, follow these steps:

. Click on the blue hyperlinked title of the patron's request.

. Click the _Add to Selection List_ button.

. Fill out the requested information. You can either add it to an existing selection list or a new one.

. After you save the record, the request's _Add to Selection List_ button will change to a _View Selection List_ button that allows you to view the status of this patron request at a later time.

. You can then use your Library's typical ordering process to purchase the item your patron has requested.

