{
    "BARCODE_PROMPT": "Barcode: ",
    "USERNAME_PROMPT": "User name: ",
    "CANCEL_BUTTON_LABEL": "Cancel",
    "SUBMIT_BUTTON_LABEL": "Submit",
    "OK": "OK",
    "PWD_RESET_RESPONSE_TITLE": "Password reset response",
    "PWD_RESET_SUBMIT_SUCCESS": "Your request to begin the password reset process has been processed. If your account has a valid email address, you should soon receive an email containing further instructions for resetting your password.",
    "PWD_RESET_SUBMIT_ERROR": "The system could not process your request for a password reset. Please try again, or contact circulation staff for assistance.",
    "PWD_RESET_SUBMIT_STATUS": "Sending request...",
    "PWD_RESET_FORGOT_PROMPT": "Forgot your password?",
    "PWD_RESET_FORM_TITLE": "Request password reset",
    "PWD_RESET_SUBMIT_PROMPT": "To begin the password reset process, enter either your barcode or user name in the form below and click 'Submit'",
	"CREATE_MFHD": "Add MFHD Record",
	"CREATED_MFHD_RECORD": "Created MFHD record for ${0}",
	"DELETE_MFHD": "Delete Record",
	"DELETE_MFHD_CONFIRM": "Are you sure you want to delete this serial record?",
	"DELETED_MFHD_RECORD": "Deleted MFHD record ${0}",
	"EDIT_MFHD_RECORD": "Edit Record",
	"EDIT_MFHD_MENU": "Edit Holdings",
	"EDIT_PROPERTIES": "Edit Properties",
	"BASIC_HOLDINGS": "Volumes",
	"BASIC_HOLDINGS_ADD": "Additional Volume Information",
	"INDEX_HOLDINGS": "Indexes",
	"INDEX_HOLDINGS_ADD": "Additional Index Information",
	"CURRENT_HOLDINGS": "Current volume",
	"CURRENT_INDEXES": "Current indexes",
	"CURRENT_SUPPLEMENTS": "Current supplements",
	"HOLDINGS_TABLE_CAPTION": "Holdings summary (${0})",
	"INCOMPLETE_VOLUMES": "Incomplete volumes",
	"MISSING_VOLUMES": "Missing volumes",
	"ONLINE_VOLUMES": "Online volumes",
	"SAVE_MFHD_LABEL": "Save MFHD",
	"SUPPLEMENT_HOLDINGS": "Supplements",
	"SUPPLEMENT_HOLDINGS_ADD": "Additional Supplement Information",
    "PLACE_HOLD": "Place hold",
    "HOLD_STATUS_PLURAL": "hold # ${0} of ${1} total holds and ${2} potential items",
    "HOLD_STATUS_SINGULAR": "hold # ${0} of ${1} total holds and ${2} potential item",
    "MORE": "More",
    "MORE_COPIES_FULL_RECORD": "... more copies listed in full record",
    "SOURCE_CANNOT_HAVE_COPIES": "Records from ${0} cannot have copies."
}
