{
	"CREATE_MFHD": "Add MFHD Record",
	"CREATED_MFHD_RECORD": "Created MFHD record for ${0}",
	"DELETE_MFHD": "Delete Record",
	"DELETED_MFHD_RECORD": "Deleted MFHD record ${0}",
	"EDIT_MFHD_RECORD": "Edit Record",
	"EDIT_MFHD_MENU": "Edit Holdings",
	"EDIT_PROPERTIES": "Edit Propeties",
	"HOLDINGS": "Previous volumes",
	"INDEXES": "Previous indexes",
	"CURRENT_HOLDINGS": "Current volume",
	"CURRENT_INDEXES": "Current indexes",
	"CURRENT_SUPPLEMENTS": "Current supplements",
	"HOLDINGS_TABLE_CAPTION": "Holdings summary (${0})",
	"INCOMPLETE_VOLUMES": "Incomplete volumes",
	"MISSING_VOLUMES": "Missing volumes",
	"ONLINE_VOLUMES": "Online volumes",
	"SAVE_MFHD_LABEL": "Save MFHD",
	"SUPPLEMENTS": "Previous supplements"
}
