New open-ils.auth.login API
^^^^^^^^^^^^^^^^^^^^^^^^^^^
The open-ils.auth service has a new API for requesting an authentication
token.  It performs the same steps as the 
open-ils.auth.authenticate.init and .complete APIs in a single call,
using the bare password.  No intermediate password hashing is required.

The paramters are the same as the .complete call with a few modifications.

1. Using the generic "identifier" parameter in combination with the
   "org" parameter allows the API to reliably determine if an identifier
   value is a username or barcode.  The caller is no longer required to 
   make that determination up front.  

2. The 'nonce' parameter is no longer used.

Upgrade Notes
+++++++++++++

The new open-ils.auth.login API must be added to the list of <log_protect>
API's in the opensrf_core.xml file.

Sample diff:

[code,sh]
---------------------------------------------------------------------
--- a/Open-ILS/examples/opensrf_core.xml.example
+++ b/Open-ILS/examples/opensrf_core.xml.example
@@ -180,6 +180,7 @@ Example OpenSRF bootstrap configuration file for Evergreen
     <log_protect>
       <match_string>open-ils.auth.authenticate.verify</match_string>
       <match_string>open-ils.auth.authenticate.complete</match_string>
+      <match_string>open-ils.auth.login</match_string>
       <match_string>open-ils.auth_proxy.login</match_string>
       <match_string>open-ils.actor.patron.password_reset.commit</match_string>
       <match_string>open-ils.actor.user.password</match_string>
---------------------------------------------------------------------

