{
	CONFIRM_DELETE: "Are you sure you want to delete ${0}?",
	CONFIRM_EXIT: "There are unsaved changes to one or more organizational units. Click OK to save these changes, or Cancel to abandon them.",
	ERROR_CREATING_CHILD: "Problem creating child Organizational Unit",
	ERROR_DELETING: "Problem deleting ${0}",
	ERROR_DELETING_LAST: "Cannot delete ${0}, you need at least one.",
	ERROR_FETCHING_HOLDS: "Problem fetching Holds Address for ${0}",
	ERROR_FETCHING_HOURS: "Problem fetching hours of operation for ${0}",
	ERROR_FETCHING_ILL: "Problem fetching ILL Address for ${0}", 
	ERROR_FETCHING_MAILING: "Problem fetching Mailing Address for ${0}", 
	ERROR_FETCHING_ORGS: "Problem fetching organizational unit data",
	ERROR_FETCHING_PHYSICAL: "Problem fetching Physical Address for ${0}", 
	ERROR_FETCHING_TYPES: "Problem fetching organizational unit type data",
	ERROR_ORPHANS: "Cannot delete ${0}, ${1} subordinates still exist.",
	ERROR_SAVING_HOO: "Problem saving Hours of Operation data for ${0}",
	ERROR_SAVING_DATA: "Problem saving data for ${0}",
	ERROR_SAVING_HOLDS: "Problem saving Holds Address data for ${0}", 
	ERROR_SAVING_ILL: "Problem saving ILL Address data for ${0}", 
	ERROR_SAVING_MAILING: "Problem saving Mailing Address data for ${0}", 
	ERROR_SAVING_PHYSICAL: "Problem saving Physical Address data for ${0}", 
	LABEL_NEW_BRANCH: "New Branch",
	STATUS_DELETED: "${0} deleted", 
	STATUS_EDITING: "Now editing ${0}",
	SUCCESS_CREATING_CHILD: "New child Organizational Unit created for ${0}",
	SUCCESS_SAVE: "Saved changes to ${0}",
	SUCCESS_SAVING_HOO: "Hours of Operation updated for ${0}",
	SUCCESS_SAVING_HOLDS: "Saved changes to the Holds Address of ${0}",
	SUCCESS_SAVING_ILL: "Saved changes to the ILL Address of ${0}",
	SUCCESS_SAVING_MAILING: "Saved changes to the Mailing Address of ${0}",
	SUCCESS_SAVING_PHYSICAL: "Saved changes to the Physical Address of ${0}"
}
