{
	"CONFIRM_DELETE": "Are you sure you want to delete ${0}?",
	"CONFIRM_EXIT": "There are unsaved changes to one or more copy statuses. Click OK to save these changes, or Cancel to abandon them.",
	"ERROR_CALLING_METHOD": "Problem calling method to create new copy status",
	"ERROR_CREATING_STATUS": "Problem creating new Status",
	"ERROR_DELETING": "Problem deleting ${0}",
	"ERROR_FETCHING_STATUSES": "Problem fetching statuses",
	"ERROR_SAVING_STATUS": "Problem saving ${0}",
	"HOLDABLE": "Holdable",
	"ID": "ID",
	"NAME": "Name",
	"OPAC_VISIBLE": "OPAC Visible",
	"STATUS_DELETED": "${0} deleted", 
	"SUCCESS_CREATING_STATUS": "New ${0} status created",
	"SUCCESS_SAVE": "Saved changes to ${0}",
	"TRANSLATION": "Translation",
}
