{
	"CONFIRM_DELETE": "Are you sure you want to delete ${0}?",
	"CONFIRM_EXIT_AOU": "There are unsaved changes to one or more organizational units. Click OK to save these changes, or Cancel to abandon them.",
	"CONFIRM_EXIT_CAM": "There are unsaved changes to one or more ${0} codes. Click OK to save these changes, or Cancel to abandon them.",
	"CONFIRM_EXIT_CCS": "There are unsaved changes to one or more copy statuses. Click OK to save these changes, or Cancel to abandon them.",
	"CONFIRM_EXIT_PGT": "There are unsaved modified permission maps. Click OK to save these changes, or Cancel to abandon them.",
	"CONFIRM_EXIT_PPL": "There are unsaved modified permissions. Click OK to save these changes, or Cancel to abandon them.",
	"CONFIRM_UNSAVED_CHANGES": "There are unsaved changes to one or more organization types. Click OK to save these changes, or Cancel to abandon them.",
	"ERROR_CALLING_METHOD_AOUT": "Problem calling method to create child organization type",
	"ERROR_CALLING_METHOD_CAM": "Problem calling method to create new ${0}",
	"ERROR_CALLING_METHOD_CCS": "Problem calling method to create new copy status",
	"ERROR_CALLING_METHOD_PERM_MAP": "Problem calling method to create new permission map",
	"ERROR_CALLING_METHOD_PGT": "Problem calling method to create child Group",
	"ERROR_CALLING_METHOD_PPL": "Problem calling method to create new permission",
	"ERROR_CREATING_CHILD_AOU": "Problem creating child organizational unit",
	"ERROR_CREATING_CHILD_AOUT": "Problem creating child organization type",
	"ERROR_CREATING_CHILD_GROUP": "Problem creating child Group",
	"ERROR_CREATING_PERMISSION": "Problem creating new Permission",
	"ERROR_CREATING_PERM_MAP": "Problem creating new Permission Map",
	"ERROR_CREATING_STATUS": "Problem creating new Status",
	"ERROR_DELETING_LAST_AOU": "Cannot delete ${0}, you need at least one organization unit.",
	"ERROR_DELETING_LAST_AOUT": "Cannot delete ${0}. You need at least one organization type.",
	"ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}",
	"ERROR_DELETING": "Problem deleting ${0}",
	"ERROR_FETCHING_GROUPS": "Problem fetching groups",
	"ERROR_FETCHING_HOLDS": "Problem fetching Holds Address for ${0}",
	"ERROR_FETCHING_HOURS": "Problem fetching hours of operation for ${0}",
	"ERROR_FETCHING_ILL": "Problem fetching ILL Address for ${0}",
	"ERROR_FETCHING_MAILING": "Problem fetching Mailing Address for ${0}",
	"ERROR_FETCHING_ORGS": "Problem fetching organizational unit data",
	"ERROR_FETCHING_PERM_MAPS": "Problem fetching perm maps",
	"ERROR_FETCHING_PERMS": "Problem fetching perms",
	"ERROR_FETCHING_PHYSICAL": "Problem fetching Physical Address for ${0}",
	"ERROR_FETCHING_STATUSES": "Problem fetching statuses",
	"ERROR_FETCHING_TYPES_AOUT": "Problem fetching organizational unit types",
	"ERROR_ORPHANS": "Cannot delete ${0}, ${1} subordinates still exist.",
	"ERROR_SAVING_DATA": "Problem saving data for ${0}",
	"ERROR_SAVING_DATA_CAM": "Problem saving data for ${0} ${1}",
	"ERROR_SAVING_HOLDS": "Problem saving Holds Address data for ${0}",
	"ERROR_SAVING_HOO": "Problem saving Hours of Operation data for ${0}",
	"ERROR_SAVING_ILL": "Problem saving ILL Address data for ${0}",
	"ERROR_SAVING_MAILING": "Problem saving Mailing Address data for ${0}",
	"ERROR_SAVING_PERM_DATA": "Problem saving permission data for ${0}",
	"ERROR_SAVING_PHYSICAL": "Problem saving Physical Address data for ${0}",
	"ERROR_SAVING_STATUS": "Problem saving ${0}",
	"HOLDABLE": "Holdable",
	"ID": "ID",
	"LABEL_CODE": "Code",
	"LABEL_DEPTH": "Depth",
	"LABEL_DESCRIPTION": "Description",
	"LABEL_GRANTABLE": "Grantable",
	"LABEL_NEW_BRANCH": "New Branch",
	"LABEL_NEW_GROUP": "New Group",
	"LABEL_NEW_TYPE": "New Type",
	"LABEL_TRANSLATION": "Translation",
	"LABEL_VALUE": "Value",
	"NAME": "Name",
	"OPAC_VISIBLE": "OPAC Visible",
	"STATUS_DELETED": "${0} deleted",
	"STATUS_EDITING": "Now editing ${0}",
	"SUCCESS_CREATING_CHILD_AOU": "New child Organizational Unit created for ${0}",
	"SUCCESS_CREATING_CHILD_AOUT": "New child Organization Type created for ${0}",
	"SUCCESS_CREATING_CODE": "New ${0} ${1} created",
	"SUCCESS_CREATING_PERMISSION": "New ${0} permission created",
	"SUCCESS_CREATING_STATUS": "New ${0} status created",
	"SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted",
	"SUCCESS_NEW_CHILD_GROUP": "New child Group created for ${0}",
	"SUCCESS_NEW_PERM_MAP": "New permission map created",
	"SUCCESS_SAVE_PERM": "Saved permission changes to ${0}",
	"SUCCESS_SAVE": "Saved changes to ${0}",
	"SUCCESS_SAVING_DATA": "Saved changes to ${0}",
	"SUCCESS_SAVING_HOLDS": "Saved changes to the Holds Address of ${0}",
	"SUCCESS_SAVING_HOO": "Hours of Operation updated for ${0}",
	"SUCCESS_SAVING_ILL": "Saved changes to the ILL Address of ${0}",
	"SUCCESS_SAVING_MAILING": "Saved changes to the Mailing Address of ${0}",
        "SUCCESS_SAVING_PHYSICAL": "Saved changes to the Physical Address of ${0}",
        "TRANSLATION": "Translation",
        "END_SURVEY": "End Survey Now",
        "SURVEY_SAVE_ADD": "Save Question & Add Answer",
        "SURVEY_DELETE_QUESTION": "Delete Question & Answers",
        "SURVEY_DELETE_ANSWER": "Delete Answer",
        "SURVEY_SAVE_CHANGES": "Save Changes",
        "SURVEY_ADD_ANSWER": "Add Answer",
        "SURVEY_ANSWER": "Answer:",
        "SURVEY_QUESTION": "Question:",
        "SURVEY_ID": "<h3>Survey ID # ${0}</h3>",
        "SURVEY_FOOT_LABEL": "<h3>Questions & Answers</h3>"
}

