{
	"CONFIRM_DELETE": "Are you sure you want to delete ${0}?",
	"CONFIRM_EXIT": "There are unsaved modified Permission Maps! OK to save these changes, Cancel to abandon them.",
	"ERROR_CALLING_METHOD": "Problem calling method to create child Group",
	"ERROR_CALLING_METHOD_PERM_MAP": "Problem calling method to create new Permission Map",
	"ERROR_CREATING_CHILD_GROUP": "Problem creating child Group",
	"ERROR_CREATING_PERMISSION": "Problem creating new Permission",
	"ERROR_CREATING_PERM_MAP": "Problem creating new Permission Map",
	"ERROR_DELETING": "Problem deleting ${0}",
	"ERROR_DELETING_PERM_MAPPING": "Problem deleting permission mapping ${0}",
	"ERROR_FETCHING_GROUPS": "Problem fetching groups",
	"ERROR_FETCHING_PERMS": "Problem fetching perms",
	"ERROR_FETCHING_PERM_MAPS": "Problem fetching perm maps",
	"ERROR_FETCHING_TYPES": "Problem fetching types",
	"ERROR_SAVING_DATA": "Problem saving data for ${0}",
	"ERROR_SAVING_PERM_DATA": "Problem saving permission data for ${0}",
	"LABEL_CODE ": "Code",
	"LABEL_DEPTH": "Depth",
	"LABEL_GRANTABLE": "Grantable",
	"LABEL_NEW_GROUP": "New Group",
	"STATUS_DELETED": "${0} deleted",
	"STATUS_EDITING": "Now editing ${0}",
	"SUCCESS_DELETED_PERM_MAP": "Permission mapping deleted",
	"SUCCESS_NEW_CHILD_GROUP": "New child Group created for ${0}",
	"SUCCESS_NEW_PERM_MAP": "New permission map created",
	"SUCCESS_SAVE": "Saved changes to ${0}",
	"SUCCESS_SAVE_PERM": "Saved permission changes to ${0}"
}
