= Administering shelving locations =
:toc:

== Creating new shelving locations ==

. Click _Administration_.
. Click _Local Administration_.
. Click _Shelving Locations Editor_.
. Type the name of the shelving location.
. In _OPAC Visible_, choose whether you would like items in this shelving location
  to appear in the catalog.
. In _Hold Verify_, 
. In _Checkin Alert_, choose whether you would like a routing alert to appear
  when an item in this location is checked in. This is intended for special
  locations, such as 'Display', that may require special handling, or that
  temporarily contain items that are not normally in that location.
+
NOTE: By default, these alerts will only display when an item is checked in, _not_
when it is used to record an in-house use.
+
To also display these alerts when an item in your location is scanned for in-house
use, go to Administration > Local Administration > Library Settings Editor and
set _Display shelving location check in alert for in-house-use_ to True.
+
. If you would like a prefix or suffix to be added to the call numbers of every
  volume in this location, enter it.
. If you would like, add a URL to the _URL_ field.  When a URL is entered in
  this field, the associated shelving location will display as a link in the Public
  Catalog summary display. This link can be useful for retrieving maps or other
  directions to the shelving location to aid users in finding material.
. If you would like to override any item-level circulation/hold policies to
  make sure that items in your new location can't circulate or be holdable,
  choose _No_ in the appropriate field.  If you choose _Yes_, Evergreen will
  use the typical circulation and hold policies to determine circulation
  abilities.

== Deleting shelving locations ==

You may only delete a shelving location if:
. it doesn't contain any items, or
. it only contains deleted items.

Evergreen preserves shelving locations in the database, so no statistical information
is lost when a shelving location is deleted.

== Modifying shelving location order ==

. Go to _Administration_.
. Go to _Local Administration_.
. Click _Shelving Location Order_.
. Drag and drop the locations until you are satisfied with their order.
. Click _Apply changes_.


== Shelving location groups ==

.Use case
****
Mayberry Public Library provides a scope allowing users to search for all
children's materials in their library. The library's children's scope
incorporates several shelving locations used at the library, including Picture
Books, Children's Fiction, Children's Non-Fiction, Easy Readers, and Children's
DVDs. The library also builds a similar scope for YA materials that incorporates
several shelving locations.
****

This feature allows staff to create and name sets of shelving locations to use as
a search filter in the catalog.  OPAC-visible groups will display within the
library selector in the Public Catalog.  When a user selects a group
and performs a search, the set of results will be limited to records that have
items in one of the shelving locations within the group.  Groups can live at any
level of the library hierarchy and may include shelving locations from any parent
org unit or child org unit.

NOTE: To work with Shelving Location Groups, you will need the ADMIN_COPY_LOCATION_GROUP
permission.

=== Create a Shelving Location Group ===

. Click Administration ->  Local Administration -> Shelving Location Groups.
. At the top of the screen is a drop down menu that displays the org unit tree.
  Select the unit within the org tree to which you want to add a shelving location group.
  The shelving locations associated with the org unit appear in the Shelving Locations column.
. In the column called _Location Groups_, click _New_.
. Choose how you want the shelving location group to display to patrons in the catalog's
  org unit tree in the OPAC. By default, when you add a new shelving location group, the
  group displays in the org unit tree beneath any branches or sub-libraries of its
  parental org unit.  If you check the box adjacent to Display above orgs, then the
  group will appear above the branches or sub-libraries of its parental org unit.
. To make the shelving location group visible to users searching the public catalog, check
  the box adjacent to Is OPAC visible?
. Enter a _Name_ for the shelving location group.
. Click Save. The name of the Shelving Location Group appears in the Location Groups.
. Select the shelving locations that you want to add to the group, and click Add. The shelving 
  locations will populate the middle column, Group Entries.
. The shelving location group is now visible in the org unit tree in the catalog. Search
  the catalog to retrieve results from any of the shelving locations that you added to
  the shelving location group.

=== Order Shelving Location Groups ===

If you create more than one shelving location group, then you can order the groups in the
org unit tree.

. Click Administration -> Local Administration -> Shelving Location Groups.
. Three icons appear next to each location group. Click on the icons to drag the shelving 
  location groups into the order in which you would like them to appear in the catalog.
. Search the catalog to view the reorder of the shelving location groups.

