== Patron Loader ==

A new script for bulk loading and updating patrons from the server now exists in Open-ILS/src/support-scripts called patron_loader.pl.  It is installed to <prefix>/bin (/openils/bin/patron_loader.pl for standard installs).  It can be run manually or from cron.

=== Sample invocation:

[source,bash]
-----------------
./patron_loader.pl --db evergreen --dbhost myserver -dbuser admin --dbpw demo123 --file sample.csv --org_unit INNS --date_format "MM/DD/YYYY" --default_password 4444 --alert_message "patron has left swim cap at desk"  --debug
-----------------

=== Required parameters:

 --file path to the CSV file used as the data source
 --org_unit the org unit name of the org unit patrons are being loaded for
   used to match mapped variables

=== Optional parameters:

 --help or --h shows the help

 Database settings loaded by default from opensrf.xml
 --db the Evergreen database (defaults to the one established in opensrf.xml)
 --dbuser the user of the Evergreen database
 --dbhost the ip or domain name of the Evergreen database
 --dbport Evergreen database port, defaults to 5432

 --delimiter defaults to a comma can be any other delimiter usable by TEXT::CSV
 --debug using this will assume you do not want to commit
   any database transactions and will print the SQL that would do so to STDOUT
 --matchpoint defaults to 'usrname', can also be 'cardnumber'
 --date_format used if dates are not in a 'YYYY-MM-DD' format
 --ident_type available as a field but rarely used in export sources so it can
   be specified from the command line
 --default_password allows you to define a default password for accounts where one
   is not defined in the file, be very careful, this option is dangerous as it
   _will_ overwrite existing passwords
   if some rows have a passwd value and the default is used the default will only
   be used where the column is null
 --alert_message this is meant for scenarios where the script is being used for bulk
   loading students and an alert message is needed such as "verify address"
   it only adds an alert and does not check for duplications
   sending library will be set to the org unit used in the parameters
 --alert_title defaults to 'Needs Staff Attention', only appears when --alert_message
   is defined
 --profile if no profile is given in the file one can be specified by parameter,
   if a combination of parameter and in file is used the parameter will be used as
   a fall back from the file
 --home_org if no library is provided in the file it can be overridden by this, like
   similar settings if a column with library is present but null in a given row
   this will be used instead; expects short org name
 --fill_with_matchpoint
   if set will allow you to only have cardnumber or usrname but it must also
   be your matchpoint, e.g. if you have a cardnumber but not username and cardnumber
   if your matchpoint with this set the cardnumber will be used for both
 --nobootstrap do not load DB config from opensrf.xml

=== Required Columns:

* *cardnumber* - unless using usrname as matchpoint and --fill_with_matchpoint is used
* *usrname* - unless using cardnumber as matchpoint and --fill_with_matchpoint is used
* *profile* - unless --profile is used
* *home_library* - unless --home_org is used
* *family_name*
* *first_given_name*

Although data for the above columns are optional in some situations the columns still need to exist in the file.

=== Optional Columns:

 net_access_level
 second_given_name
 pref_first_given_name
 name_keywords
 email
 day_phone
 evening_phone
 other_phone
 expire_date
 ident_type   <-- needs id value, not string
 ident_value
 passwd       <-- if not supplied for a new user a random one will be created on NULL or empty string
 add1_street1
 add1_street2
 add1_cit
 add1_county
 add1_state
 add1_country
 add1_post_code
 add2_street1
 add2_street2
 add2_cit
 add2_county
 add2_state
 add2_country
 add2_post_code
 statcat_name1
 statcat_value1
 statcat_name2
 statcat_value2
 statcat_name3
 statcat_value3
 photo_url

=== Mapping:

Not all data sources can customize the data exported to the CSV so some mapping is allowed.


The *config.patron_loader_header_map* table allows for mapping incoming header names to ones that
are natively expected.  For example, imagine that a school wants to use the 'uid' as
password and the column header will always read 'uid' then you can enter it like this:

 import_header: 'uid'
 default_header: 'passwd'

Two value types can currently be mapped as well, 'home_library' and 'profile' in patron_loader_value_map.
These map values in their respective columns instead of the headers.  For example, imagine a
school who exports student profiles of 'Middle School' and 'High School' but both need to load
as the Evergreen profile of 'Student'.  It would be represented with two entries:

 mapping_type: 'profile'
 import_value: 'Middle School'
 native_value: 'Student'

 mapping_type: 'profile'
 import_value: 'High School'
 native_value: 'Student'

You can also map home libraries like this:

 mapping_type: 'home_library'
 import_value: 'South West Elementary'
 native_value: 'BR1'

As a convention the Evergreen database column names are mostly used for the actor.usr
columns but it was found in testing that home_ou was very confusing so the label of
'library' is used instead and internally adjusted to use 'home_ou'.

The column ident_type is treated specially.  It is required by actor.usr and does not
have a default but usually doesn't correspond to a exported value from others systems
so it defaults to '3' or 'Other' but you can define it through an optional parameter.

=== Overview:

The script is very conservative checking for an existing cardnumber and usrname.  If
either is found on an account that differs from the one using the match point then it
will skip adding or updating that user.  The match point specified is considered
authoritative and it will update the matching account unless debug is on.

Currently only two set of address columns are supported add1_foo and add2_foo. The script
assumes the addresses being added are authoritative mailing addresses, removes any existing
mailing addresses, adds these and sets the user's mailing_address field to the one from the
addr1_street1 field or addr2_street1 if there is no addr1_street1.  If only a partial address
is given the entire address will be written so long as there is a street1.  Empty strings will
be used for the other values.  If there is no address given then addresses will not be
touched.  Part of the aggressiveness of removing non-specified addresses is to ensure
identifying information for patrons is removed when updating, especially for the use case
of schools bulk updating juveniles.

=== Database and Logging:

The database holds a *actor.patron_loader_log* table that logs sessions and failed rows.

