== Quipu eCard Integration ==

The eCARD integration builds on previous work, and adds a generic method of integrating with Quipu’s eCARD service. This feature creates a location for a new Quipu-provided registration form that can be configured to send information to Quipu for address verification, as well as several new library settings related to the integration.

This bypasses the regular Pending Patrons workflow.

Due to the nature of how Quipu configures eCARD on their end, it is strongly recommended that libraries work directly with Quipu to test before implementation.

This work includes methods and other code intended to support future related work for Quipu's eRENEW service.

=== Changes to database, procedures, and library settings === 

* Adds IDL entry for "ILS User Change History".
* Adds `guardian_email` column to `actor.usr` table.
* Adds `evergreen.json_delta` stored procedure.
* Adds `actor.generate_barcode` stored procedure.
* Adds `actor.usr_delta_history` table.
* Adds `actor.record_usr_delta` stored procedure.
* Adds `record_usr_delta trigger` to actor.usr table. 
** This monitors updates to the user table and records the change in configured columns to the `actor.usr_delta_history`, which is labeled "ILS User Change History" in the reporter. By default, it only records changes in the `last_update_time column`, and the trigger itself is disabled by default. This can be reconfigured by the Database Adminstrator.
* Adds `erenew` column to `permission.grp_tree`.
* Adds a "PATRON_TEMP_RENEWAL" penalty to `config.standing_penalty`.
* Adds an `ecard_vendor` password type. This type of password can only be set by the Database Adminstator.
* Adds various library settings for Ecards in general, and for Quipu integration specifically.
* Adds library settings for configuring Guardian Email for patron registration.
* Adds an A/T hook for `au.create.ecard`, and an A/T template and environment variables for sending email for Ecard verification.
* Upgrades library settings for early adopters.

=== Note for Early Adopters ===

Evergreen sites that were early adopters for Quipu integration (i.e., already using a Quipu integration prior to this work) may review `Open-ILS/src/sql/Pg/LP1902937-convert-quipu-early-adopt.sql` after building Evergreen.

However, this SQL does not completely isolate changes made to support the new integration. Libraries are strongly advised to coordinate with Quipu before actually upgrading to or past this update to Evergreen. 
