{
    "FAILURE": "Capture failed",
    "SUCCESS": "Capture succeeded",
    "UNKNOWN_PROBLEM": "An unknown problem occurred during capture attempt.",
    "CAPTURED_NOTHING": "Didn't capture anything.",
    "NO_PAYLOAD": "We did not receive further information from the server about this attempt to capture.",
    "HERES_WHAT_WE_KNOW": "The following information is available about the failed capture:",
    "CAPTURE_INFO": "Capture Information",
    "CAPTURE_BRESV_DATES": "Reservation time:",
    "CAPTURE_BRESV_BRSRC": "Resource barcode:",
    "CAPTURE_BRESV_PICKUP_LIB": "Pickup library:",
    "CAPTURE_CAUSES_TRANSIT": "This item is now in transit!",
    "CAPTURE_TRANSIT_SOURCE": "From:",
    "CAPTURE_TRANSIT_DEST": "To:",
    "BARCODE": "Barcode",
    "TITLE": "Title",
    "AUTHOR": "Author",
    "RESERVED": "Reserved for patron",
    "REQUEST": "Request time",
    "DURATION": "Reserved from",
    "SLIP_DATE": "Slip date",
    "PRINTED_BY": "Printed by",
    "AT": "at",
    "PRINT": "<u>P</u>rint",
    "PRINT_ACCESSKEY": "P",
    "TRANSIT": "*** TRANSIT ***",
    "RESERVATION_SHELF": "RESERVATION SHELF",
    "NEEDS_ROUTED_TO": "This item need to be routed to",

    "AUTO_capture_heading": "Capture Reserved Resources",
    "AUTO_resource_barcode": "Enter barcode:",
    "AUTO_pickup_lib_selector": "Pickup library:",
    "AUTO_ATTR_VALUE_capture": "Capture"
}
