{
    "NO_PATRON_BARCODE": "Please enter a patron barcode.",
    "RESERVATIONS_NO_RESPONSE": "No response from server when asking for reservations.",
    "RESERVATIONS_ERROR": "Error communicating with server (asking for reservations):",
    "PICKUP_NO_RESPONSE": "No response from server when attempting pickup.",
    "PICKUP_ERROR": "Error communicating with server (attempting pickup):",
    "RETURN_NO_RESPONSE": "No response from server when attempting return.",
    "RETURN_ERROR": "Error communicating with server (attempting return):",
    "RETURN_SUCCESS": "Return successful.",
    "SELECT_SOMETHING": "You have not selected any reservations.",
    "NO_SUCH_RETURNABLE_RESOURCE": "No such returnable resource.",
    "RETURNABLE_RESOURCE_ERROR": "Error looking up returnable resource:",
    "NOTICE_CHANGE_OF_PATRON":
        "Note that the resource scanned was out on reservation to a different\npatron than the last resource you scanned.  If this is not\nexpected, stop to examine outstanding reservations for your patron\nor on the resource.",

    "AUTO_h1": "Reservations Pickup",
    "AUTO_return_h1": "Reservations Return",
    "AUTO_patron_barcode": "Enter patron barcode:",
    "AUTO_barcode_type": "Return by barcode of",
    "AUTO_in_bresv": "Patron has returned these resources today:",
    "AUTO_ready_bresv": "Patron has these reservations ready for pickup:",
    "AUTO_out_bresv": "Patron currently has these reservations out:",
    "AUTO_no_ready_bresv": "Patron has no reservations ready for pickup at this time.",
    "AUTO_no_out_bresv": "Patron has no more reservations out at this time.",
    "AUTO_no_in_bresv": "Patron has not returned any resources today.",
    "AUTO_patron": "Patron",
    "AUTO_resource": "Resource",
    "AUTO_ATTR_VALUE_go": "Go",
    "AUTO_ATTR_VALUE_reset": "Clear / New Patron",
    "AUTO_ATTR_VALUE_pickup": "Pick up",
    "AUTO_ATTR_VALUE_return": "Return",
    "ADDRESS": "${0}\n${1}\n${2}, ${3} ${4}",
    "COPY_ALERT": "${0}:\n${1}\n\nDo you wish to process it anyway?"
}
