= Item Alerts Administration =
:toc:

== Item Alert Types ==

Item Alert Types are created and managed in *Administration -> Local Administration -> Item Alert Types*. Item Alert Types define the action and behavior of an alert message type. The Alert Types included in a stock installation of Evergreen are:

* Normal checkout
* Normal checkin
* Normal renewal
* Checkin of missing copy
* Checkin of lost-and-paid copy
* Checkin of damaged copy
* Checkin of claims-returned copy
* Checkin of long overdue copy
* Checkin of claims-never-checked-out copy
* Checkin of lost copy
* Checkout of missing copy
* Checkout of lost-and-paid copy
* Checkout of damaged copy
* Checkout of claims-returned copy
* Checkout of long overdue copy
* Checkout of claims-never-checked-out copy
* Checkout of lost copy
* Normal checkout at circ lib
* Normal checkin at circ lib
* Normal renewal at circ lib
* Normal checkout at owning lib
* Normal checkin at owning lib
* Normal renewal at owning lib

To create a new Item Alert Type:

. Navigate to *Administration -> Local Administration -> Item Alert Types*.
. Select *Create* at the top-left of the screen and fill out the following fields as needed
.. _Name_: name of the Item Alert Type.
.. _Active_: indicates if the alert type is currently in use (Yes) or not (No)
.. _State_: indicates the Copy Status of the item at the time of the event.
.. _Event_: the action that takes place in the ILS to trigger the alert.
.. _Scope Org Unit_: indicates which org unit(s) the alert type will apply to.
.. _Next Status_: can be used with temporary Checkin Alerts only. If a nextstatus is configured, staff will be presented with a list of statuses to choose from when the item is checked in.
.. _Renewing?_: indicates if the alert should appear during a renewal.
.. _Invert location?_: if set to yes, this setting will invert the following two settings.
+
NOTE: For example, if an alert is set to appear at the Circulating Library only, inverting the location will cause the alert to appear at all libraries except the Circulating Library.
+
.. _At Circulation Library?_: indicates if the alert should appear at the circulation library only.
.. _At Owning Library?_: indicates if the alert should appear at the owning library only.
. Click *Save*.

To edit an existing Item Alert Type:

. Navigate to *Administration -> Local Administration -> Item Alert Types*.
. Double click on the type, or right-click and select *Edit*, or single click and select *Actions -> Edit*.
. Make your desired changes to the existing item alert configuration and
click *Save*.

== Item Alert Suppression ==

The Item Alert Suppression interface can be used to suppress alert types
at a specific org unit. Suppression of alerts will adhere to the
organization unit hierarchy. For example, if an alert is suppressed at
the System level, it will be suppressed for all descendent branches.

To suppress an alert type:

. Navigate to *Administration -> Local Administration -> Item Alert Suppression*.
. Select *New Item Alert Suppression* and select the Alert Type that you want to suppress from the drop down menu.
. Next, select the Organizational Unit at which the alert should be suppressed.
. Click Save.

NOTE: Suppression will not prevent staff members from adding an alert type to an item, but it will prevent that alert from displaying at the selected Organizational Unit.