{
    'CREATE_PO_ASSETS_CONFIRM' : "This will create bibliographic, call number, and copy records for this purchase order in the ILS.\n\nContinue?",
    'ROLLBACK_PO_RECEIVE_CONFIRM' : "This will rollback receipt of all copies for this purchase order.\n\nContinue?",
    'XUL_RECORD_DETAIL_PAGE' : 'Record Details',
    'DELETE_LI_COPIES_CONFIRM' : 'This will delete the last ${0} copies in the table.  Proceed?',
    'NO_PO_RESULTS': "No results",
    'PO_HEADING_ERROR' : "Unexpected problem building virtual combined PO",
    'CONFIRM_SPLIT_PO': "Are you sure you want to split this purchase order into\none purchase order for every constituent line item?",
    'DFA_NOT_ALL': "Could not record all of your applications of distribution forumulas.",
    'APPLY': "Apply",
    'RESET_FORMULAE': "Reset Formulas",
    'OUT_OF_COPIES': "You have applied distribution formulas to every copy.",
    'ONE_LI_ATTR_SEARCH_AT_A_TIME': "You cannot both type in an attribute value search and search for an uploaded file of terms at the same time.",
    'LI_ATTR_SEARCH_CHOOSE_FILE': "Select file with search terms",
    'LI_ATTR_SEARCH_TOO_LARGE': "That file is too large for this operation.",
    'SELECT_AN_LI_ATTRIBUTE': "You must select an LI attribute.",
    'NO_RESULTS': "No results.",
    'EXPORT_SAVE_DIALOG_TITLE': "Save field values to a file",
    'EXPORT_SHORT_LIST': "Not all of the selected items had the attribute '${0}'.\nChoose OK to save those values that could be found.",
    'EXPORT_EMPTY_LIST': "No values for attribute '${0}' found."
}
