= About This Documentation =

This guide was produced by the Evergreen Documentation Interest Group (DIG),
consisting of numerous volunteers from many different organizations. The DIG
has drawn together, edited, and supplemented pre-existing documentation
contributed by libraries and consortia running Evergreen that were kind enough
to release their documentation into the creative commons. Please see the
xref:shared:attributions.adoc#attributions[Attributions] section for a full list of authors and
contributing organizations. Just like the software it describes, this guide is
a work in progress, continually revised to meet the needs of its users, so if
you find errors or omissions, please let us know, by contacting the DIG
facilitators at docs@evergreen-ils.org.

== Documentation Versions ==

This site includes documentation for Evergreen version 3.6 and above. To change the version, select one from the dropdown list at the top-right of the menu bar, or at the bottom of the left-hand sidebar.

For versions 3.5 and previous, visit the https://docs.evergreen-ils.org/[Evergreen Documentation Version Index].
