= Managing Authorities =
:toc:

== Introduction ==

This section describes how you can create, import, view, modify, merge, and delete authority records in Evergreen.

== Creating Authorities ==
Currently in Evergreen to create a new authority record, as opposed to importing an authority record, you 
need to have a bib record open in the bib MARC editor. 

* For example, if you want to create a new author 
authority you need to have a bib record that has a bib 1xx or 7xx tag with the main entry filled out. 
* Then you need to right click on that 1xx or 7xx tag. In the context menu that shows up, select _Create 
New Authority from this field_, then select either _Create Immediately_ or _Create and Edit..._. 
* If you 
choose _Create and Edit..._, after the authority MARC editor opens you need to click on the _Save_ button
to finally add the new authority record to your system.


[[importing_authority_records_from_the_staff_client]]
== Importing Authorities ==
. Click *Cataloging -> MARC Batch Import/Export.*
. You may create a queue to better track this import project.  If you do not create a new queue, it will automatically put your records into a default queue named *-*.
. Don't set a value for Holdings Import Profile, because this doesn't apply to authority records.
. Select a file of authority data and put it in the *File to Upload* field.
. Make sure all the settings are correct, then press *Upload.*
+
The screen displays "Uploading... Processing..." to show that the records
are being transferred to the server, then displays a progress bar to show
the actual import progress. When the staff client displays the progress
bar, you can disconnect your staff client safely. Very large batches of
records might time out at this stage.

. Evergreen will automatically assign a thesaurus based on the *Subj* fixed field, which is character 11 in the 008 field.
. Evergreen will also try to determine who edited the record (based on the MARC 905u field or the user performing the import) and set the edit date, which you can view
when you examine the record in the future.

. Once the import is finished, the staff client displays the results of
the import process. You can manually display the import progress by
selecting the _Inspect Queue_ tab of the _MARC Batch Import/Export_
interface and selecting the queue name. By default, the staff client does
not display records that were imported successfully; it only shows records
that conflicted with existing entries in the database. The screen shows
the overall status of the import process in the top right-hand corner,
with the Total and Imported number of records for the queue.


[TIP]
=================
If you are importing authorities from an external vendor and want to track this, you may wish to set a unique Record Source. This source will be visible in the MARC
Editor and in the 901$s field of the imported authority records.
=================


=== Setting up Authority Record Match Sets ===
. Click *Cataloging -> MARC Batch Import/Export.*
. Click *Record Match Sets.*
. If you have sufficient privileges, you will be able to click on the *New Match Set*.  If you are unable to do so, check that you have the ADMIN_IMPORT_MATCH_SET permission.
. Give your new set a descriptive name, an owning library, and a match set type of *authority.*
. Click on the blue hyperlinked name of the match set you just created to add criteria.
. You can match against MARC tag/subfield entries or against a record's normalized heading.

[NOTE]
=================
Evergreen's database stores normalized authority headings in a format that includes the thesaurus. This way, record match sets will not match terms from other thesauri, even if the term is very similar.
=================

[TIP]
=================
Evergreen's internal identifier is in the 901c field. If you have previously exported authority record -- perhaps for an external vendor to do authority cleanup work -- and you want to import them back into your catalog, you may wish to include the 901c field in your match set.
=================

== Viewing and Editing Authority Records by Database ID ==

The authority record retriever allows catalogers to retrieve a specific
authority record using its database ID.  Catalogers can
find those IDs in subfield $0 of matching fields in
bibliographic records.

To use the authority record retriever:

. Click *Cataloging -> Retrieve Authority Record by ID*.
. Type in the ID number of the authority record you are
interested in. Don't include any prefixes, just the ID
number. 
. Click *Submit*.
. View or edit the authority record as needed.


== Manage Authorities Interface ==

In Evergreen to view, edit, merge, and delete authority records you would use the *Manage Authorities* interface 
through the *Cataloging* menu.



=== Searching for authorities ===

To search for authorities in your system, first select the *Cataloging* menu and then select *Manage Authorities*. 
Then proceed to fill out the search form. 

. Type in your _Search Term_
. Select an _Authority type_, types currently include: Author, Subject, Title, Topic 
. Click on the _Submit_ button


The authority search results will include the following elements from left to right:

* _Actions_ menu, which can be used to select actions that affect the corresponding authority record. Actions include: 
_Edit_, _Mark for Merge_, _Delete_
* Count of how many bibs are linked to the corresponding authority
* Main entry of the authority, i.e the authority tag 1xx value
* _Control set_ value, with LoC being the default, but others can be added
* Authority Subject heading system/thesaurus, for example a value of "a" means authority originated from the Library of Congress 
 (http://www.loc.gov/marc/authority/ad008.html)


*Library of Congress list of thesaurus values:*

* '' = Alternate no attempt to code
* a = Library of Congress Subject Headings
* b = LC subject headings for children's literature
* c = Medical Subject Headings
* d = National Agricultural Library subject authority file
* k = Canadian Subject Headings
* n = Not applicable
* r = Art and Architecture Thesaurus
* s = Sears List of Subject Headings
* v = Repertoire de vedettes-matiere
* z = Other
* | = No attempt to code


==== Editing authority records ====

Editing an authority record (or merging two authority records) can cause its linked bibliographic records to also update.  For example,
if you correct a spelling error in the 150 field of a subject authority record, the relevant 650 field in linked bibliographic records 
will also be updated to reflect the correct spelling.

[TIP]
=================
When a bib record is automatically updated as a result of the modification of a linked authority record, the bib record's "Last Edit Date/
Time" and "Last Editing User" fields will be updated to match the time of the update and the editor of the authority record.  If you'd
prefer that these fields not be automatically updated, you can set the _ingest.disable_authority_auto_update_bib_meta_ setting to true in the
Library Settings Editor.
=================

