= Working with holdings templates =
:toc:

Setting up holdings templates can save a lot of time when creating items, and they
also improve consistency and accuracy.  Any time you find yourself creating multiple
items with the same item-level data, you may wish to create a holdings template
to automate that process.

== Creating a new holdings template ==

* Open _Administration_ -> _Local Administration_ -> _Holdings Template Editor_.
* Select the desired template attributes by moving through the fields in the
editor. The attributes you've changed will appear in green. If you want to
start this process over, you can click the _Clear_ button in the top right
corner of the screen.
* Type a name for your template into the box labeled _Template_ at the top
of the screen.
* Press the _Save_ button.

== Using a holdings template ==

Whenever you see the holdings editor, you can use data from your templates.

* In the _Template_ menu, choose the template you wish to use.
* Click _Apply_.
* Make any other necessary changes.

