= Antora Docs build procedure

:idseparator: -

== Using generate_docs.pl

This tool should perform all of the steps in "Doing it Manually", automatically. This tool requires some command line arguments and also requires some prerequisites.

=== Installing Node

Be sure and have Node installed.

see https://github.com/nvm-sh/nvm#installation-and-update[Installing Node]

[source,bash]
----
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
----

=== Antora pre-reqs

Once Node is installed, follow the Antora prereqs

Summarized from https://docs.antora.org/antora/2.3/install/linux-requirements/[Antora pre-reqs]

[source,bash]
----
$ nvm install --lts
----

=== Install Ansible

There is one peice of the puzzle using Ansible at the moment. Better get that installed.

[source,bash]
----
$ sudo apt-get install ansible
----

=== Run generate_docs.pl

This tool does the rest of the work. You will be requried to supply these things:

[cols=2*]
|===

|base-url
|[eg: http//examplesite.org]

|tmp-space
|[Writable path where we stage antora UI repo and the antora HTML, eg: ../../tmp]

|html-output
|[Path where you want the generated HTML files to go, eg: /var/www/html]

|antora-ui-repo
|[git link to a repo, could be community repo: https://gitlab.com/antora/antora-ui-default.git]

|antora-version
|[target version of antora, eg: 2.1]

|===

Example:

[source,bash]
----
$ cd Evergreen/docs-antora
$ ./generate_docs.pl \
--base-url http//examplesite.org/prod \
--tmp-space ../../tmp \
--html-output /var/www/html/prod \
--antora-ui-repo https://git.evergreen-ils.org/eg-antora.git \
--antora-version 2.3

----

NOTE: This tool will create two folders within the temp space folder path: "staging" and "antora-ui". These folders will be erased and re-created with each execution.



== Doing it all manually

[source,bash]
----
$ git clone git://git.evergreen-ils.org/working/Evergreen.git
$ git clone git://git.evergreen-ils.org/eg-antora.git
$ cd Evergreen
$ git checkout collab/blake/LP1848524_antora_ize_docs
----

First we have to install antora:
Summarized from 
https://docs.antora.org/antora/2.1/install/install-antora/

[source,bash]
----
$ cd docs-antora
# (we want to install into directory as opposed to globally)
$ npm i @antora/cli@2.1 @antora/site-generator-default@2.1
----


Now, install the ui pre-reqs building
lifted from:
https://docs.antora.org/antora-ui-default/set-up-project/

[source,bash]
----
$ cd ../../eg-antora
$ npm install
$ npm gulp-bundle
----

At this point you should find a file in:

NOTE: build/ui-bundle.zip

Now you can build the website. But you may want to edit the file:

NOTE: docs-antora/site.yml

Because the output folder for the website is defaulted to 

NOTE: /var/www/html/prod

And the default web URL is:

NOTE: http://localhost/prod

Build:

[source,bash]
----
$ cd ../Evergreen/docs-antora
antora site.yml
----

If all went well - then you will have the site built in the output folder that was configured in site.yml!

Interesting reading related to Antora and AsciiDoc and AsciiDoctor

NOTE: https://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/

NOTE: https://blog.anoff.io/2019-02-15-antora-first-steps/

NOTE: https://owncloud.org/news/owncloud-docs-migrating-antora-pt-1-2/


== Search stuff

First you need to have ansible installed

NOTE: If you want to manually edit the file, you don't need to install ansible

[source,bash]
----
$ sudo apt-get -y install ansible
----

Now, let's run through the antora-lunr procedure:

NOTE: Lifted from the base install notes from the  https://github.com/Mogztter/antora-lunr[ git repo]


[source,bash]
----
$ ansible-playbook setup_lunr.yml

----

This should have edited this file: node_modules/@antora/site-generator-default/lib/generate-site.js
as outlined in the git repo notes

Now, install the lunr bits (from docs-antora folder)

[source,bash]
----
$ npm i antora-lunr
----

And now, you can re-generate the site but this time with the search box:

[source,bash]
----
$ DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr antora site.yml
----

