Evergreen 2_12 Release Notes
============================
:toc:
:numbered:

Upgrade notes
-------------

New Features
------------



Administration
~~~~~~~~~~~~~~



Apache Internal Port Configuration Option
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apache configuration now supports a new variable which allows admins to
specify the port used by Apache to handle HTTP traffic.  The value is
used for HTTP requests routed from Perl handlers back to the same Apache
instance, like added content requests.  Use this when running Apache
with a non-standard port, typical with a proxy setup.  Defaults to "80".

[source,conf]
-------------------------------------------------------------------
<Location /eg>
    ...
    PerlSetVar OILSWebInternalHTTPPort "7080"
    ...
</Location>
-------------------------------------------------------------------




Fix COPY_STATUS_LONGOVERDUE.override Permission Typo
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The existing permission was incorrectly created with a code of
COPY_STATUS_LONGOVERDUE.override, while the event thrown requires a
permission with a code of COPY_STATUS_LONG_OVERDUE.override.  This
update changes the permission code to match what the event requires.





Hold Targeter V2 Repairs and Improvements
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* Make the batch targeter more resilient to a single-hold failure.
* Additional batch targeter info logging.
* Set OSRF_LOG_CLIENT in hold_targeter_v2.pl for log tracing
* Removes the confusingly named --target-all option
 ** The same behavior can be achieved by using --retarget-interval "0s"
* Removes --skip-viable (see --soft-retarget-interval below)

New --next-check-interval Option
++++++++++++++++++++++++++++++++
Specify how long after the current run time the targeter will retarget
the currently affected holds. Applying a specific interval is useful
when the retarget-interval is shorter than the time between targeter
runs.

For example, if the targeter is run nightly at midnight with a
--retarget-interval 36h, you would set --next-check-interval to 48hr,
since the holds won't be processed again until 48 hours later. This
ensures that the org unit closed date checks are looking at the correct
date. 

This setting overrides the default behavior of calculating the next 
retarget time from the retarget-interval.

New --soft-retarget-interval Option
+++++++++++++++++++++++++++++++++++
This is a replacement for (and rebranding of) the --skip-viable option. 
The new option allows for time-based soft-targeting instead simple binary 
on/off soft-targeting.

How soft-targeting works:
* Update hold copy maps for all affected holds
* Holds with viable targets (on the pull list) are otherwise left alone.
* Holds without viable targets are retargeted in the usual manner. 





Remove JSPAC Redirects
^^^^^^^^^^^^^^^^^^^^^^
Future versions of Evergreen will no longer contain automatic redirects
from JSPAC URLs to TPAC URLs, with the exception of myopac.xml, given
that the JSPAC is no longer supported.  Existing sites, however, may
wish to retain JSPAC redirects in their Apache configuration files since
JSPAC URLs may still be used in the wild to access their catalogs.

The original JSPAC URL redirects are all retained in the file 
Open-ILS/examples/jspac_redirects.conf for reference.




OPAC
~~~~



Download Checkout History CSV Fixed for Large Number of Circulations
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Downloading checkout history as a CSV from My Account has been fixed
for users with a large circulation history.  Previously, this would
time out for patrons with more than 100 or so circulations.

This feature no longer uses the action/trigger mechanism and the OPAC
now generates the CSV directly.  The old action/trigger code is still
present in the database and should be removed at some point in the
near future.




Reports
~~~~~~~



Fix to reporter.classic_current_circ view
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The `reporter.classic_current_circ` view, which is part of some
extra views defined in `Open-ILS/src/sql/Pg/example.reporter-extension.sql`,
has been fixed to not exclude loans for patrons who do not have a
billing address set. Users of this view should rerun
`Open-ILS/src/sql/Pg/example.reporter-extension.sql` during upgrade.



Miscellaneous
-------------

Fixes to patron name/username search indexes
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
When using pg_restore to restore an Evergreen database, some of the
indexes used to speed up patron searches on names and usernames
could be lost.

This release fixes the underlying issue and re-creates the indexes
in question.

Details
+++++++
When using pg_restore to restore an affected database, the
"unaccent" indexes on actor.usr would not be created due to an
unqualified function reference in evergreen.unaccent_and_squash.

The function will be replaced to resolve the search path issue,
and the following indexes on actor.usr will be dropped and then
re-created:

  * actor_usr_first_given_name_unaccent_idx;
  * actor_usr_second_given_name_unaccent_idx;
  * actor_usr_family_name_unaccent_idx;
  * actor_usr_usrname_unaccent_idx;

This will be done even if the indexes are already present, and may
take a few minutes on a database with many patrons.


Acknowledgments
---------------
The Evergreen project would like to acknowledge the following
organizations that commissioned developments in this release of
Evergreen:

TODO

We would also like to thank the following individuals who contributed
code, translations, documentations patches and tests to this release of
Evergreen:

TODO


We also thank the following organizations whose employees contributed
patches:

TODO

We regret any omissions.  If a contributor has been inadvertently
missed, please open a bug at http://bugs.launchpad.net/evergreen/
with a correction.

