= Evergreen 3.17 Release Notes =
:toc:
:numbered:
:toclevels: 3

== Evergreen 3.17-beta ==

=== Upgrade notes ===

==== Removal of `open-ils.permacrud` ====

The `open-ils.permacrud` service has been removed from this release. To remove it
from existing installations, do the following:

* Update `opensrf_core.xml` to remove `open-ils.permacrud` from
  the list of services on the public router.
* Update `opensrf.xml` to remove the entire `<open-ils.permacrud>` element from
  the `<apps>` element and remove `<appname>open-ils.permacrud</appname>`
  from any `<activeapps>` elements where it is present.

If you have the `perldoc` command installed, you can use the following
command to locate the path on disk of the `PermaCrud.pm` file, which
is no longer required and can be removed:

[source,sh]
-----------------------------------------------------------------
perldoc -l OpenILS::Application::PermaCrud
-----------------------------------------------------------------

==== Changes to Dependencies ====

This release:

* Adds support for Debian 13 "Trixe" (https://bugs.launchpad.net/evergreen/+bug/2120581[Bug 2120581])
* Adds support for PostgreSQL 18 (https://bugs.launchpad.net/evergreen/+bug/2131086[Bug 2131086])
* Removes support for PostgreSQL 13 (https://bugs.launchpad.net/evergreen/+bug/2131086[Bug 2131086])

=== New Features, Enhancements, and Improvements ===

Evergreen 3.17-beta contains the following improvements over prior
releases of Evergreen. Please note that if a bug was fixed in any
prior release of Evergreen, it will generally not appear in these
release notes.

:leveloffset: +3


= API =


== Notification Opt-Ins by Notice Type API / Settings ==

Creates a set of notification group entries to collect user settings related
to opting in to different types of notices (email, sms, phone, print).

Adds an API which reports on which notice types a user is opted in to and 
allows for batch opt in/out for a collection of notice types.

Handles Action/Trigger opt-in user settings and the generic 'opac.hold_notify' 
user setting which combines different notice types into a single setting.

=== Configuration ===

Add Action/Trigger notification opt-in user settings to one of the provided 
setting groups to enable it for global opt in/out.

=== Example Srfsh Query ===

This example sets the value of the specified notice types and returns opt-in 
information about all known notice types for the provided (or logged in) user.

`_default_hold_notify` is a special type which indicates whether the 
notification is opted in/out via the generic `opac.hold_notify` user setting.
This is not reported as `opac.hold_notify` since its value is not boolean like
other opt-in settings.

If all notices of a given grouping (e.g. 'sms') are true, the user is 
in effect opted in to 'sms' notices.  If the values are mixed, which can
happen via other work flows / staff client, it's up to the caller to 
decide how to interpret the data.

request open-ils.actor open-ils.actor.settings.notify.opt_ins.crud "AUTHTOKEN" 221 {"email": true, "phone": true, "sms": true}
- - - - - - - - - - - - - - - - - - - - - - - - - -
{
  "sms": {
    "sms.notices.all": true,
    "_default_hold_notify": true
  },
  "phone": {
    "_default_hold_notify": true
  },
  "print": {
    "_default_hold_notify": false
  },
  "email": {
    "_default_hold_notify": true,
    "email.notices.all": true
  }
}

In this example "email.notices.all" and "sms.notices.all" are local test settings.

=== "SMS" vs. Text ===

For internal consistency, this feature uses the label/code "sms" as a stand-in 
for text notices in general.

= Cataloging =

* Reimplement a slim version of the previous Working Items list to allow applying specific changes to user-selected subsets of items in the Holdings Editor. (https://bugs.launchpad.net/evergreen/+bug/1998645[Bug 1998645])
* Item Buckets can now be imported from CSV files (https://bugs.launchpad.net/evergreen/+bug/1208093)[Bug 1208093]
* Adds five item import attributes for use during MARC import: floating, loan duration, fine level, age-based hold protection, and quality (https://bugs.launchpad.net/evergreen/+bug/1376427[Bug 1376427])
* Monograph parts that have been marked as deleted can now be displayed in the parts grid (https://bugs.launchpad.net/evergreen/+bug/2120735)[Bug 2120735]
* Restores the ability to Unset some fields in the Holdings Editor. (https://bugs.launchpad.net/evergreen/+bug/2121686[Bug 2121686])

= Circulation =


== Opt Out of Year and Postal Code in Aged Transactions  ==

Evergreen now supports additional org unit settings to control what information is included when you age holds and circulations.  Now the year of the patron's birth date and postal code can be set to null rather than populate the aged transaction tables when a transaction is aged.  The following settings control this behavior for holds and circulations respectively:  

----
circ.do_not_retain_year_of_birth_on_aged
circ.do_not_retain_post_code_on_aged
holds.do_not_retain_year_of_birth_on_aged
holds.do_not_retain_post_code_on_aged
----

If you wish to not retain any of these fields on existing aged holds and circulations you should run the following SQL on the database.  

to remove postal codes on aged holds:

----
UPDATE action.aged_hold_request SET usr_post_code = NULL WHERE usr_post_code IS NOT NULL;
----

to remove birth years on aged holds:

----
UPDATE action.aged_hold_request SET usr_birth_year = NULL WHERE usr_birth_year IS NOT NULL;
----

to remove postal codes on aged circulations:

----
UPDATE action.aged_circulation SET usr_post_code = NULL WHERE usr_post_code IS NOT NULL;
----

to remove birth years on aged circulations:

----
UPDATE action.aged_circulation SET usr_birth_year = NULL WHERE usr_birth_year IS NOT NULL;
----


== User Settings in Patron Summary ==

User settings, such as default phone number, default hold
pickup library, and hold notification format, are now
displayed as part of the patron summary pane when searching
patrons or retrieving a patron record.


== Other Improvements ==

* Makes privacy waiver more prominent on patron summary bar (https://bugs.launchpad.net/evergreen/+bug/1897121[Bug 1897121])
* Adds actions to the items out, renew, and checkin interfaces to email receipts to the patron. (https://bugs.launchpad.net/evergreen/+bug/1783642[Bug 1783642])
* Staff can delete inactive patron barcodes via the web client. (https://bugs.launchpad.net/evergreen/+bug/1917761[Bug 1917761])
* Add Library Group-based hold and circ policy configuration, and the ability to clone individual hold and circ policies. (https://bugs.launchpad.net/evergreen/+bug/1968186[Bug 1968186])
* The patron summary now includes the number of overdue items in the patron's group if other patrons in the groups have overdue items. (https://bugs.launchpad.net/evergreen/+bug/2043051[Bug 2043051])
* Adds option to set hold expiration at time of hold placement in OPAC. (https://bugs.launchpad.net/evergreen/+bug/2119563[Bug 2119563])


= Client =


== Staff client locales configurable in the database ==

Previously, system administrators could define which locales should display
in the staff client by editing a file called environment.prod.ts.

In this release, these locales are instead configured in the config.i18n_locale
database table.  To enable the cs-CZ locale in the staff client, for example,
you can issue this SQL query:

[source,sql]
-------------
UPDATE config.i18n_locale SET staff_client=TRUE WHERE code='cs-CZ';
-------------

Any locales with a true staff_client value will appear in the locale picker, and
will be listed as options when translating terms within the staff client.

== Other Improvements ==

* Allows case insensitive grid filter searching for text columns in tables with low cardinality, except log or history tables. (https://bugs.launchpad.net/evergreen/+bug/1910424[Bug 1910424])
* Search box in Angular Reporter is changed from "Search templates for string" to "Search templates for keyword/text" to be more user-friendly. (https://bugs.launchpad.net/evergreen/+bug/2139299[Bug 2139299])

= Public Catalog =


== ChiliFresh Cover Images ==

ChiliFresh is now avaialble as an added content source for cover
images. To enable (after getting a subscription), edit `opensrf.xml`
and set the `added_content/module` value to `OpenILS::WWW::AddedContent::Chilifresh`.

The `added_content/base_url` value will also need to be set, typically to
"https://content.chilifresh.com/".

If you are supplied a "generic" code by ChiliFresh, that goes in the
`added_content/generic` element in `opensrf.xml`.



== Ability to enable Stackmap added content ==

Creates two library settings to allow easier management of added content from Stackmap.

  - Stackmap: Enable (true/false)
  - Stackmap: Identifier (account code provided by Stackmap)

== Other Improvements ==

* Accessibility updates to Preferences > Other Settings page. (https://bugs.launchpad.net/evergreen/+bug/2115525[Bug 2115525])
* Removes autofocus from OPAC basic search form keyword input (https://bugs.launchpad.net/evergreen/+bug/2115443[Bug 2115443])

= Architecture =

== Removal of `open-ils.permacrud` service ==

The deprecated service `open-ils.permacrud` has been removed.
Any remaining external clients using that service should switch
to using the `open-ils.pcrud` service.

= Development =

== Angular CLI No Longer Installed Globally ==

The Evergreen installation process no longer installs
the Angular CLI globally.  All angular commands are
still available with the `npx` prefix.  For example,
`ng build` is now `npx ng build`.

Anybody who relies on the Angular CLI being installed
globally can install it with `npm i -g @angular/cli@^18.0`

== Other Improvements ==

* The Angular unit test suite is now run as a GitHub action (https://bugs.launchpad.net/evergreen/+bug/2116743[Bug 2116743])
* Add an option to speed up prerequisite installation. (https://bugs.launchpad.net/evergreen/+bug/2125838[Bug 2125838])


:leveloffset: 1


== Acknowledgments ==

The Evergreen project would like to acknowledge the following
organizations that commissioned developments in this release of
Evergreen:

* BC Libraries Cooperative
* PaILS

We would also like to thank the following individuals who contributed
code, translations, documentations patches and tests to this release of
Evergreen:

* Andrea Buntz Neiman
* Bill Erickson
* Blake Graham-Henderson
* Brett French
* Brian Kennedy
* Chris Sharp
* Christine Burns
* Christine Morgan
* Dan Briem
* Devon Bates
* Elizabeth Davis
* Galen Charlton
* Gina Monti
* Ian Skelskey
* Jane Sandberg
* Jason Boyer
* Jason Etheridge
* Jason Stephenson
* Jeff Godin
* Jennifer Pringle
* Jennifer Weston
* Josh Stompro
* Katie Greenleaf Martin
* Lindsay Stratton
* Llewellyn Marshall
* Martha Driscoll
* Mary Llewellyn
* Michele Morgan
* Mike Rylander
* Ranelle Irwin
* Rogan Hamby
* Sarah Cruz
* Scott Angel
* Shula Link
* Stephanie Leary
* Steven Mayo
* Susan Morrison
* Tara Kunesh
* Terran McCanna
* Tiffany Little
* Ying-Hsiang Huang

We also thank the following organizations whose employees contributed
patches, documentation, and testing:

* Bibliomation
* CW MARS
* Equinox Open Library Initiative
* GPLS
* KCLS
* LARL
* MOBIUS
* PaILS
* NC Cardinal
* NOBLE
* TADL

We regret any omissions.  If a contributor has been inadvertently
missed, please open a bug at http://bugs.launchpad.net/evergreen/
with a correction.


