Evergreen System Administration at your Library
===============================================
Documentation Interest Group
:doctype: book
:toc:
:numbered:

Introduction
============

include::shared/about_this_documentation.adoc[]

This guide to Evergreen is intended to meet the needs of system administrators
at local libraries who use the staff client for their day-to-day work.

It is organized into Parts, Chapters, and Sections addressing key
aspects of the software. 

Copies of this guide can be accessed in PDF and HTML formats from http://docs.evergreen-ils.org/.



include::shared/about_evergreen.adoc[]

:leveloffset: -1

include::admin/web_client-login.adoc[]

include::admin/web-client-browser-best-practices.adoc[]

:leveloffset: 0

include::shared/workstation_settings.adoc[]

:leveloffset: -1

include::admin/librarysettings.adoc[]

:leveloffset: 0

Organizational Unit administration
==================================

:leveloffset: 1

include::admin_initial_setup/describing_your_organization.adoc[]

include::admin/lsa-standing_penalties.adoc[]

:leveloffset: 0

include::admin_initial_setup/ordering_materials.adoc[]

include::admin/acquisitions_admin.adoc[]



// Cat
Cataloging administration
=========================

include::admin/authorities.adoc[]

include::admin/cn_prefixes_and_suffixes.adoc[]

include::admin/lsa-statcat.adoc[]

include::admin/MARC_Import_Remove_Fields.adoc[]

include::admin/copy_tags_admin.adoc[]

include::admin/MARC_RAD_MVF_CRA.adoc[]

include::admin/restrict_Z39.50_sources_by_perm_group.adoc[]

include::admin/copy_locations.adoc[]

:leveloffset: 1

include::admin_initial_setup/importing_via_staff_client.adoc[]

:leveloffset: 0
// Circ
Circulation administration
==========================


Circulation policies
--------------------

This section discusses the initial setup and subsequent troubleshooting and refinement of circulation policies.


:leveloffset: 2

include::admin_initial_setup/borrowing_items.adoc[]

include::admin/autorenewals.adoc[]

include::admin/circulation_limit_groups.adoc[]

include::admin/hold_driven_recalls.adoc[]


:leveloffset: 0

include::admin/copy_statuses.adoc[]

include::admin/circing_uncataloged_materials.adoc[]

include::admin/patron_registration.adoc[]

include::admin/patron_self_registration.adoc[]


Holds, transits, and resource sharing
-------------------------------------

:leveloffset: 1

include::admin/age_hold_protection.adoc[]

include::admin/Best_Hold_Selection_Sort_Order.adoc[]

include::admin/Org_Unit_Proximity_Adjustments.adoc[]

:leveloffset: 2

include::admin/floating_groups.adoc[]

:leveloffset: 0

Working with money
------------------

This section discusses how to manage and report on payments accepted by your library's circulation processes.

Accepting credit card payments
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Evergreen can interface with services like Authorize.net, stripe, PayPal, or Payflow to allow users to pay
fines and other charges in the Public Catalog.  Credit card settings can be configured in the <<lse-credit-cards,Library Settings Editor>>.

:leveloffset: 1

include::admin/desk_payments.adoc[]

:leveloffset: 0

include::admin/allowed_payments.adoc[]

:leveloffset: 1

include::circulation/user_buckets.adoc[]

:leveloffset: 0


Circulation timesavers and workflows
------------------------------------

This section describes specific settings that may increase efficiency or accuracy at some libraries, but might not be suitable for every library.

:leveloffset: 1

include::admin/lsa-barcode_completion.adoc[]

include::admin/lsa-address_alert.adoc[]

:leveloffset: 0

Library closures
----------------

This section describes both everyday closures and specific details suitable for school and academic libraries that operate on a term or semester system.

include::admin/hours.adoc[]

include::admin/closed_dates.adoc[]

include::admin/emergency_closing_handler.adoc[]

:leveloffset: 1

include::admin_initial_setup/hard_due_dates.adoc[]

:leveloffset: 0

include::admin/booking-admin.adoc[]

include::admin/receipt_template_editor.adoc[]

:leveloffset: 1

include::circulation/self_check_configuration.adoc[]

:leveloffset: 0

// SEARCH ADMIN
Search Settings
===============

include::admin/search_settings_web_client.adoc[]

include::admin/popularity_badges_web_client.adoc[]

:leveloffset: -1

include::admin/multilingual_search.adoc[]

include::admin/infrastructure_auth_browse.adoc[]

include::admin/virtual_index_defs.adoc[]

:leveloffset: 0


// Patron UX
Patron User Experience Administration
=====================================

Introduction
------------

This section describes settings for the OPAC, including patron self-registration and other functionalities.

include::admin/SMS_messaging.adoc[]

include::opac/linked_libraries.adoc[]

include::admin_initial_setup/designing_your_catalog.adoc[]


Reports
=======

Introduction
------------

Learn how to create and use reports in Evergreen.

include::reports/reporter_folder.adoc[]

include::reports/reporter_create_templates.adoc[]

include::reports/reporter_generating_reports.adoc[]

include::reports/reporter_view_output.adoc[]

include::reports/reporter_cloning_shared_templates.adoc[]

include::reports/reporter_running_recurring_reports.adoc[]

include::reports/reporter_template_terminology.adoc[]

include::reports/reporter_template_enhancements.adoc[]

include::reports/reporter_export_usingpgAdmin.adoc[]



// Staff

Staff administration
====================

Introduction
------------

This section describes how to administer staff accounts.

:leveloffset: 1

include::admin_initial_setup/describing_your_people.adoc[]

:leveloffset: 0

include::admin/permissions.adoc[]

include::admin/lsa-work_log.adoc[]

include::admin/staff_client-recent_searches.adoc[]

// Other

Other administration
====================

Introduction
------------

This section describes other staff client administrator tasks.

include::admin/actiontriggers.adoc[]

:leveloffset: 0

include::shared/attributions.adoc[]

include::shared/end_matter.adoc[]
