site:
  title: Evergreen Documentation
  start_page: docs:shared:about_this_documentation.adoc
  url: http://localhost/prod
content:
  sources:
  - url: ../
#    - url: git://git.evergreen-ils.org/Evergreen.git
    branches: [main, rel_3_14, rel_3_13, rel_3_12, rel_3_11, rel_3_10, rel_3_9, rel_3_8, rel_3_7, rel_3_6]
    start_path: docs
ui:
  bundle:
    url: ./../../eg-antora/build/ui-bundle.zip

output:
  dir: /var/www/html/prod

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true

