== Angular Record Buckets ==

This work moves the Record Buckets feature into a new and reimagined Angular interface, and adds several new feature improvements.

Feature improvements include:

* Reimplementation of the main buckets interfaces in Angular with accessibility and usability improvements.
* New bucket sharing options, including sharing with organizational units, sharing with specific users, and read-write sharing as well as read-only sharing.
* Transfer Bucket Ownership, where users can transfer their bucket to another user.
* Favorites option, allowing a staff user to "star" a bucket to indicate it is a favorite.
* Direct import of either Bib IDs or TCNs, both from a text file as well as in an upload modal.
* Ability to send reports output directly to a new or specified bucket.
* Addition of a new _Buckets_ subtab in the staff catalog interface, displaying a user's favorite and most recently viewed buckets.
* Addition of a quick-add feature in the staff catalog search results list, where a user can add a record directly to a recent or a favorite bucket.
* New buckets admin options available from within the buckets interface, where those with admin permissions can do the following:
** Transfer ownership of others' buckets.
** Edit bucket options and sharing for others' buckets.
* Disambiguation of duplicate bucket entries via a new _Bucket Entry ID_ field, allowing users to intentionally add duplicates and/or remove accidental duplicates.

In addition to feature improvements, this work addresses functional bugs related to record buckets, including:

* https://bugs.launchpad.net/evergreen/+bug/1837933[Bug 1837933] - Record links don't work if ID column is hidden in record bucket query
* https://bugs.launchpad.net/evergreen/+bug/1771568[Bug 1771568] - Record Bucket duplicates require separate removal
* https://bugs.launchpad.net/evergreen/+bug/1870151[Bug 1870151] - Open Record Bucket title in a new tab
* https://bugs.launchpad.net/evergreen/+bug/1819059[Bug 1819059] - When creating a bucket, Evergreen ignores the Publicly Visible? setting
* https://bugs.launchpad.net/evergreen/+bug/1824723[Bug 1824723] - No error message when retrieving non existing shared bucket 
* https://bugs.launchpad.net/evergreen/+bug/1870148[Bug 1870148] - Bucket contents may be removed by other users without warning
* https://bugs.launchpad.net/evergreen/+bug/2027796[Bug 2027796] - When editing a record bucket the changes save without having to click on Apply Changes
* https://bugs.launchpad.net/evergreen/+bug/2063146[Bug 2063146] - Record bucket contents still hang around in the Web client after you've deleted a bucket

This work also introduces some changes to the grid component:

* A new option to have an actions button column at the end of each row.
* Template areas before and after grid toolbar buttons, used here to insert inputs.
* Aligning the right side of the grid toolbar to more closely resemble AngularJS styles, including using the word _Actions_ for the actions menu instead of the checklist icon.

This also introduces a change to the title area in Angular screens. Instead of using the blue alert style, page titles are now left-aligned and have a template area afterward. This is intended to be used for single buttons that represent a primary action on the screen, e.g. Add New [Thing]. This change makes room for a second template area that can be placed to the right of the title, used here for a search box.


This work adds the following new permissions. Note that the _CALL_NUMBER_, _COPY_, and _USER_ permissions are placeholders for potential future work:

* TRANSFER_CONTAINER
* ADMIN_CONTAINER_BIBLIO_RECORD_ENTRY_USER_SHARE
* ADMIN_CONTAINER_CALL_NUMBER_USER_SHARE
* ADMIN_CONTAINER_COPY_USER_SHARE
* ADMIN_CONTAINER_USER_USER_SHARE
* VIEW_CONTAINER_BIBLIO_RECORD_ENTRY_USER_SHARE
* VIEW_CONTAINER_CALL_NUMBER_USER_SHARE
* VIEW_CONTAINER_COPY_USER_SHARE
* VIEW_CONTAINER_USER_USER_SHARE
* ADMIN_CONTAINER_BIBLIO_RECORD_ENTRY_ORG_SHARE
* ADMIN_CONTAINER_CALL_NUMBER_ORG_SHARE
* ADMIN_CONTAINER_COPY_ORG_SHARE
* ADMIN_CONTAINER_USER_ORG_SHARE
* VIEW_CONTAINER_BIBLIO_RECORD_ENTRY_ORG_SHARE
* VIEW_CONTAINER_CALL_NUMBER_ORG_SHARE
* VIEW_CONTAINER_COPY_ORG_SHARE
* VIEW_CONTAINER_USER_ORG_SHARE