Upgrading the Evergreen Server
------------------------------
Before upgrading, it is important to carefully plan an upgrade strategy to minimize system downtime and service interruptions.
All of the steps in this chapter are to be completed from the command line.

Software Prerequisites
~~~~~~~~~~~~~~~~~~~~~~

  * **PostgreSQL**: Version 9.4 is recommended.
    The minimum supported version is 9.3.
  * **Linux**: Evergreen 2.12.9 has been tested on Debian Jessie (8.0),
    Debian Wheezy (7.0), Ubuntu Xenial Xerus (16.04),
    and Ubuntu Trusty Tahr (14.04).
    If you are running an older version of these distributions, you may want
    to upgrade before upgrading Evergreen. For instructions on upgrading these
    distributions, visit the Debian or Ubuntu websites.
  * **OpenSRF**: The minimum supported version of OpenSRF is 2.5.0.


In the following instructions, you are asked to perform certain steps as either the *root* or *opensrf* user.

  * **Debian**: To become the *root* user, issue the `su` command and enter the password of the root user.
  * **Ubuntu**: To become the *root* user, issue the `sudo su` command and enter the password of your current user.

To switch from the *root* user to a different user, issue the `su - [user]`
command; for example, `su - opensrf`. Once you have become a non-root user, to
become the *root* user again simply issue the `exit` command.

Upgrade the Evergreen code
~~~~~~~~~~~~~~~~~~~~~~~~~~
The following steps guide you through a simplistic upgrade of a production
server. You must adjust these steps to accommodate your customizations such
as catalogue skins.

. Stop Evergreen and back up your data:
 .. As *root*, stop the Apache web server.
 .. As the *opensrf* user, stop all Evergreen and OpenSRF services:
+
[source, bash]
-----------------------------
osrf_control --localhost --stop-all
-----------------------------
+
 .. Back up the /openils directory.
. Upgrade OpenSRF. Download and install the latest version of OpenSRF from
the https://evergreen-ils.org/opensrf-downloads/[OpenSRF download page].
. As the *opensrf* user, download and extract Evergreen 2.12.9:
+
[source, bash]
-----------------------------------------------
wget https://evergreen-ils.org/downloads/Evergreen-ILS-2.12.9.tar.gz
tar xzf Evergreen-ILS-2.12.9.tar.gz
-----------------------------------------------
+
[NOTE]
For the latest edition of Evergreen, check the https://evergreen-ils.org/egdownloads/[Evergreen download page] and adjust upgrading instructions accordingly.

. As the *root* user, install the prerequisites:
+
[source, bash]
---------------------------------------------
cd /home/opensrf/Evergreen-ILS-2.12.9
---------------------------------------------
+
On the next command, replace `[distribution]` with one of these values for your
distribution of Debian or Ubuntu:
+
indexterm:[Linux, Debian]
indexterm:[Linux, Ubuntu]
+
  * `debian-jessie` for Debian Jessie (8.0) (See https://bugs.launchpad.net/evergreen/+bug/1342227[Bug 134222] if you want to use EDI)
  * `debian-wheezy` for Debian Wheezy (7.0)
  * `ubuntu-xenial` for Ubuntu Xenial Xerus (16.04) (EDI compatibility in progress)
  * `ubuntu-trusty` for Ubuntu Trusty Tahr (14.04) (See https://bugs.launchpad.net/evergreen/+bug/1342227[Bug 134222] if you want to use EDI)

+
[source, bash]
------------------------------------------------------------
make -f Open-ILS/src/extras/Makefile.install [distribution]
------------------------------------------------------------
+
. As the *opensrf* user, configure and compile Evergreen:
+
[source, bash]
------------------------------------------------------------
cd /home/opensrf/Evergreen-ILS-2.12.9
PATH=/openils/bin:$PATH ./configure --prefix=/openils --sysconfdir=/openils/conf
make
------------------------------------------------------------
+
These instructions assume that you have also installed OpenSRF under /openils/. If not, please adjust PATH as needed so that the Evergreen configure script can find osrf_config.
+
. As the *root* user, install Evergreen:
+
[source, bash]
------------------------------------------------------------
cd /home/opensrf/Evergreen-ILS-2.12.9
make STAFF_CLIENT_STAMP_ID=rel_2_12_9 install
------------------------------------------------------------
+
. As the *root* user, change all files to be owned by the opensrf user and group:
+
[source, bash]
------------------------------------------------------------
chown -R opensrf:opensrf /openils
------------------------------------------------------------
+
. As the *opensrf* user, update the server symlink in /openils/var/web/xul/:
+
[source, bash]
-----------------------------------------------------------
cd /openils/var/web/xul/
rm server
ln -sf rel_2_12_9/server server
----------------------------------------------------------
+
. As the *opensrf* user, update opensrf_core.xml and opensrf.xml by copying the
  new example files (/openils/conf/opensrf_core.xml.example and
  /openils/conf/opensrf.xml). The _-b_ option creates a backup copy of the old file.
+
[source, bash]
----------------------------------------------------------
cp -b /openils/conf/opensrf_core.xml.example /openils/conf/opensrf_core.xml
cp -b /openils/conf/opensrf.xml.example /openils/conf/opensrf.xml
----------------------------------------------------------
+
[CAUTION]
Copying these configuration files will remove any customizations you have made to them. Remember to redo your customizations after copying them.
+
. As the *opensrf* user, update the configuration files:
+
[source, bash]
-------------------------------------------------------------------------
cd /home/opensrf/Evergreen-ILS-2.12.9
perl Open-ILS/src/support-scripts/eg_db_config --update-config --service all \
--create-offline --database evergreen --host localhost --user evergreen --password evergreen
-------------------------------------------------------------------------
+
. As the *root* user, update the Apache files:
+
indexterm:[Apache]
+
Use the example configuration files in `Open-ILS/examples/apache/` (for
Apache versions below 2.4) or `Open-ILS/examples/apache_24/` (for Apache
versions 2.4 or greater) to configure your Web server for the Evergreen
catalog, staff client, Web services, and administration interfaces. Issue the
following commands as the *root* Linux account:
+
[CAUTION]
Copying these Apache configuration files will remove any customizations you have made to them. Remember to redo your customizations after copying them.
For example, if you purchased an SSL certificate, you will need to edit eg.conf to point to the appropriate SSL certificate files.
The diff command can be used to show the differences between the distribution version and your customized version. `diff <customized file> <dist file>`
+
.. Update _/etc/apache2/eg_startup_ by copying the example from _Open-ILS/examples/apache/eg_startup_.
+
[source, bash]
----------------------------------------------------------
cp /home/opensrf/Evergreen-ILS-2.12.9/Open-ILS/examples/apache/eg_startup /etc/apache2/eg_startup
----------------------------------------------------------
+
.. Update /etc/apache2/eg_vhost.conf by copying the example from Open-ILS/examples/apache/eg_vhost.conf.
+
[source, bash]
----------------------------------------------------------
cp /home/opensrf/Evergreen-ILS-2.12.9/Open-ILS/examples/apache/eg_vhost.conf /etc/apache2/eg_vhost.conf
----------------------------------------------------------
+
.. Update /etc/apache2/sites-available/eg.conf by copying the example from Open-ILS/examples/apache/eg.conf.
+
[source, bash]
----------------------------------------------------------
cp /home/opensrf/Evergreen-ILS-2.12.9/Open-ILS/examples/apache/eg.conf /etc/apache2/sites-available/eg.conf
----------------------------------------------------------

Upgrade the Evergreen database schema
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

indexterm:[database schema]

The upgrade of the Evergreen database schema is the lengthiest part of the
upgrade process for sites with a significant amount of production data.

Before running the upgrade script against your production Evergreen database,
back up your database, restore it to a test server, and run the upgrade script
against the test server. This enables you to determine how long the upgrade
will take and whether any local customizations present problems for the
stock upgrade script that require further tailoring of the upgrade script.
The backup also enables you to cleanly restore your production data if
anything goes wrong during the upgrade.

[NOTE]
=============
Evergreen provides incremental upgrade scripts that allow you to upgrade
from one minor version to the next until you have the current version of
the schema. For example, if you want to upgrade from 2.5.1 to 2.12.0, you
would run the following upgrade scripts:

- 2.5.1-2.5.2-upgrade-db.sql
- 2.5.2-2.5.3-upgrade-db.sql
- 2.5.3-2.6.0-upgrade-db.sql (this is a major version upgrade)
- 2.6.2-2.6.3-upgrade-db.sql
- 2.6.3-2.7.0-upgrade-db.sql (this is a major version upgrade)
- 2.7.0-2.7.1-upgrade-db.sql
- 2.7.1-2.7.2-upgrade-db.sql
- 2.7.2-2.7.3-upgrade-db.sql
- 2.7.3-2.7.4-upgrade-db.sql
- 2.7.4-2.8.0-upgrade-db.sql (this is a major version upgrade)
- 2.8.0-2.8.1-upgrade-db.sql
- 2.8.1-2.8.2-upgrade-db.sql
- 2.8.2-2.8.3-upgrade-db.sql
- 2.8.3-2.8.4-upgrade-db.sql
- 2.8.4-2.9.0-upgrade-db.sql (this is a major version upgrade)
- 2.9.0-2.9.1-upgrade-db.sql
- 2.9.1-2.9.2-upgrade-db.sql
- 2.9.2-2.9.3-upgrade-db.sql
- 2.9.3-2.10.0-upgrade-db.sql
- 2.10.0-2.10.1-upgrade-db.sql
- 2.10.1-2.10.2-upgrade-db.sql
- 2.10.2-2.10.3-upgrade-db.sql
- 2.10.3-2.10.4-upgrade-db.sql
- 2.10.4-2.10.5-upgrade-db.sql
- 2.10.5-2.10.6-upgrade-db.sql
- 2.10.6-2.10.7-upgrade-db.sql
- 2.10.7-2.11.0-upgrade-db.sql (this is a major version upgrade)
- 2.11.0-2.11.1-upgrade-db.sql
- 2.11.1-2.11.2-upgrade-db.sql
- 2.11.2-2.11.3-upgrade-db.sql
- 2.11.3-2.12.0-upgrade-db.sql (this is a major version upgrade)
- 2.12.0-2.12.1-upgrade-db.sql
- 2.12.1-2.12.2-upgrade-db.sql
- 2.12.2-2.12.3-upgrade-db.sql
- 2.12.3-2.12.4-upgrade-db.sql
- 2.12.4-2.12.5-upgrade-db.sql
- 2.12.5-2.12.6-upgrade-db.sql
- 2.12.6-2.12.7-upgrade-db.sql
- 2.12.7-2.12.8-upgrade-db.sql
- 2.12.8-2.12.9-upgrade-db.sql

Note that you do *not* want to run additional 2.5 scripts to upgrade to the
newest version of 2.5, since currently there is no automated way to upgrade
from 2.5.4+ to 2.6. Only upgrade as far as necessary to reach the major
version upgrade script (in this example, as far as 2.5.3).

To upgrade across multiple major versions (e.g. from 2.3.0 to 2.12.9), use
the same logic to utilize the provided major version upgrade scripts. For
example:

- 2.3-2.4.0-upgrade-db.sql
- 2.3-2.4-supplemental.sh
- (run all incremental scripts from 2.4.0 to 2.4.3)
- 2.4.3-2.5.0-upgrade-db.sql
- (run all incremental scripts from 2.5.0 to 2.5.3)
- 2.5.3-2.6.0-upgrade-db.sql
- (run all incremental scripts from 2.6.0 to 2.6.3)
- 2.6.3-2.7.0-upgrade-db.sql
- (run all incremental scripts from 2.7.0 to 2.7.4)
- 2.7.4-2.8.0-upgrade-db.sql
- (run all incremental scripts from 2.8.0 to 2.8.4)
- 2.8.4-2.9.0-upgrade-db.sql
- (run all incremental scripts from 2.9.0 to 2.9.3)
- 2.9.3-2.10.0-upgrade-db.sql
- (run all incremental scripts from 2.10.0 to 2.10.7)
- 2.10.7-2.11.0-upgrade-db.sql
- (run all incremental scripts from 2.11.0 to 2.11.3)
- 2.11.3-2.12.0-upgrade-db.sql
- (run all incremental scripts from 2.12.0 to 2.12.9)

=============

[CAUTION]
Pay attention to error output as you run the upgrade scripts. If you encounter errors
that you cannot resolve yourself through additional troubleshooting, please
report the errors to the https://evergreen-ils.org/communicate/mailing-lists/[Evergreen
Technical Discussion List].

Run the following steps (including other upgrade scripts, as noted above)
as a user with the ability to connect to the database server.

[source, bash]
----------------------------------------------------------
cd /home/opensrf/Evergreen-ILS-2.12.9/Open-ILS/src/sql/Pg
psql -U evergreen -h localhost -f version-upgrade/2.11.3-2.12.0-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.0-2.12.1-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.1-2.12.2-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.2-2.12.3-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.3-2.12.4-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.4-2.12.5-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.5-2.12.6-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.6-2.12.7-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.7-2.12.8-upgrade-db.sql evergreen
psql -U evergreen -h localhost -f version-upgrade/2.12.8-2.12.9-upgrade-db.sql evergreen
----------------------------------------------------------

[TIP]
After the some database upgrade scripts finish, you may see a
note on how to reingest your bib records. You may run this after you have
completed the entire upgrade and tested your system. Reingesting records
may take a long time depending on the number of bib records in your system.

Restart Evergreen and Test
~~~~~~~~~~~~~~~~~~~~~~~~~~
. As the *root* user, restart memcached to clear out all old user sessions.
+
[source, bash]
--------------------------------------------------------------
service memcached restart
--------------------------------------------------------------
+
. As the *opensrf* user, start all Evergreen and OpenSRF services:
+
[source, bash]
--------------------------------------------------------------
osrf_control --localhost --start-all
--------------------------------------------------------------
+
. As the *opensrf* user, run autogen to refresh the static organizational data files:
+
[source, bash]
--------------------------------------------------------------
cd /openils/bin
./autogen.sh
--------------------------------------------------------------
+
. Start srfsh and try logging in using your Evergreen username and password:
+
[source, bash]
--------------------------------------------------------------
/openils/bin/srfsh
srfsh% login username password
--------------------------------------------------------------
+
You should see a result like:
+
[source, bash]
------------------------------------------------------
Received Data: "250bf1518c7527a03249858687714376"
    ------------------------------------
    Request Completed Successfully
    Request Time in seconds: 0.045286
    ------------------------------------

    Received Data: {
       "ilsevent":0,
       "textcode":"SUCCESS",
       "desc":" ",
       "pid":21616,
       "stacktrace":"oils_auth.c:304",
       "payload":{
          "authtoken":"e5f9827cc0f93b503a1cc66bee6bdd1a",
          "authtime":420
       }

    }

    ------------------------------------
    Request Completed Successfully
    Request Time in seconds: 1.336568
    ------------------------------------
----------------------------------------------------------
+
If this does not work, it's time to do some <<install-troubleshooting-1,troubleshooting>>.
+
. As the *root* user, start the Apache web server.
+
If you encounter errors, refer to the <<install-troubleshooting-1,troubleshooting>> section 
of this documentation for tips on finding solutions and seeking further assistance
from the Evergreen community.

Review Release Notes
~~~~~~~~~~~~~~~~~~~~

Review the <<_evergreen_2_12_release_notes,2.12 release notes>> for other tasks
that need to be done after upgrading.  If you have upgraded over several 
major versions, you will need to review the release notes for each version also.
