{
    "CREATING": "Creating session ...",
    "SAVING_TAGS": "Saving tag/subfield selectors ...",
    "PERFORMING_SEARCH": "Performing search ...",
    "EXTRACTING_URLS": "Extracting URLs ...",
    "NEED_UVUS": "You must add some tag and subfield combinations.",
    "REDIRECTING": "Loading next interface ...",
    "INTERFACE_SETUP": "Setting up interface ...",
    "VERIFY_ALL": "Click 'OK' to verify ALL the URLs that belong to this session and match all your search terms.  Click 'Cancel' if the selected, visible URLs are the only ones you want verified.",
    "VERIFICATION_DIALOG": "Verifying URLs ...",
    "VERIFICATION_ATTEMPT_ID": "Verification attempt ID: ${0}",
    "NOTHING_SELECTED": "No rows are selected, so no action will be taken.",
    "REVIEW_ATTEMPT": "Review this verification attempt",
    "CLONE_SESSION": "Clone",
    "REREVIEW": "Open",
    "CLONING": "Cloning existing session ...",
    "CLONE_SESSION_NAME": "Copy of ${0}",
    "XPATH": "XPath",
    "SESSION_NAME": "Session '${0}'",
    "SELECT_MORE": "Click here to review all session URLs and/or select other URLs to verify",
    "MARC_EDITOR_LINK": "Click to open MARC Editor for this record",
    "MARC_EDITOR_TITLE": "Record ID #${0}",
    "MARC_EDITOR_SAVE_RECORD": "Save Record",
    "EDIT": "Edit"
}
