Electronic resources in the catalog
-----------------------------------

Checking out and placing holds
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Evergreen supports checking out and placing holds on
OverDrive and OneClickdigital ebook titles from within the public
catalog.  This is an experimental feature.  It is not recommended for production
use without careful testing.

When ebook integration is enabled, a "Check Out E-Item" link will be
displayed when viewing an ebook title from a supported vendor in the
catalog.  Clicking on the link allows the user to check out and download
that title from the vendor directly within the catalog.

If no copies are available for the title, a "Place Hold on E-Item" link
is displayed instead, and the user may place a hold on the title.  (Note
that some vendors require the user's account to have an email address
before permitting a hold.)

My Account includes the ability to view current ebook checkouts and
holds, download already-checked-out titles, and cancel holds.

For API integration to work, you need to request API access from the
vendor, and the vendor must have a way of authenticating your patrons.
Your Evergreen system also needs to be configured for ebook API
integration, following the instructions in the command line system
administration manual


This feature assumes that you are importing MARC records supplied by the
vendor into your Evergreen system, using Vandelay or some other MARC
import method.  This feature does not search the vendor's online
collections or automatically import vendor records into your system; it
merely augments records that are already in Evergreen.
