name: Build Docs
on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Docs Package
        run: |
          cd docs
          sed -i 's/branches.*/branches: [HEAD]/' site.yml
          perl generate_docs.pl --base-url http://example.com
      - uses: actions/upload-artifact@v2
        with:
          name: built-docs
          path: docs/output
          retention-days: 2
