name: Build Docs
on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Docs Package
        run: |
          cd docs
          sed -i 's/branches.*/branches: [HEAD]/' site.yml
          perl generate_docs.pl --base-url http://example.com
      - uses: actions/upload-artifact@v4
        with:
          name: built-docs
          path: docs/output
          retention-days: 2
  check_docs_styles:
    name: Check docs styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install asciidoctor
        run: sudo apt-get install -y asciidoctor
      - name: Install vale
        run: pip install vale
      - name: Download and install vale rules
        run: cd docs && vale sync
      - name: Check documentation against DIG style guide
        run: cd docs && vale modules
