New Bootstrap-based OPAC
^^^^^^^^^^^^^^^^^^^^^^^^

This release includes a new experimental OPAC with a cleaner, more modern design.

To enable the new OPAC design, open the _/etc/apache2/eg_vhost.conf_ file.

Find the following line:

------------------------------------------------------------------------------
PerlAddVar OILSWebTemplatePath "/openils/var/templates"
------------------------------------------------------------------------------

Add the following line directly below it:

------------------------------------------------------------------------------
PerlAddVar OILSWebTemplatePath "/openils/var/templates-bootstrap"
------------------------------------------------------------------------------

Be sure that, if you have any local customizations, that they are referenced below
this line.  This way, your customizations will still appear in the new OPAC design
(although they may need to be adjusted to better fit the new style).

You can also turn on the new OPAC for some virtual hosts only, by adding it to the
appropriate virtual host entry.  Be sure to reference the OILSWebTemplatePath for
the `templates-bootstrap` directory before referencing any local customizations
used by that virtual host.

To emphasize, the new OPAC skin is considered experimental for 3.6.x. There
are some discrepancies between its functionality and the functionality
present in the original "TPAC" skin. The Evergreen community aims to
resolve those discrepancies and make the Bootstrap skin become the default
OPAC for the Spring 2021 release (though the original TPAC skin will still
be available). Using the Bootstrap skin in production for 3.6 is at your own risk.
