== KPAC Redesign in Bootstrap ==

The Bootstrap version of the Kids' Catalog is fully accessible, mobile-friendly, and translateable. In addition,
the new version eliminates the older version's XML configuration file with a new staff client interface to improve
the ease of updating highlighted home page topics and links.

This work also fixes several outstanding KPAC bugs including issues with the login template and redirect.

=== Configuration ===

  * The Bootstrap KPAC will be used when the Bootstrap OPAC is used. This is controlled by the eg_vhost.conf file.
  * New permission group: KPAC_ADMIN - Allows access to the KPAC Topic Configuration interface.
  * New library setting: Show KPAC Link (opac.show_kpac_link) - Shows the KPAC link in the OPAC. Default is false.
  * New library setting: KPAC Audience Filter (opac.kpac_audn_filter) - Controls which items to display
based on MARC Target Audience (Audn) field. Juvenile options are: a,b,c,d,j. Default is: a,b,c,j. Please note
that the underlying Perl code has been changed to use this library setting instead of the older XML configuration
file, so libraries using the older KPAC should update this setting if they are using anything other than a,b,c,j.

=== KPAC Topic Configuration ===

The new topic administration interface is reached by going to Administration > Server Administration > KPAC Topic
Configuation. 

Topic graphics should be a minimum size of 168 x 107 pixels and need to be uploaded into the /images/kpac2/uploads
folder. Only the file name needs to be entered into the Image File Name field (for example, kpac-dinosaur.png). 

The Parent Category field should be left blank unless it is a sub-topic of another category, in which case it
should reference the parent topic's name.

The Content Type field determines what type of link a topic will be: Category, Search String, URL, or Book List.

  * Category: Category topics will open to a new page with sub-topics.
  * Search String: Fill in the Search String field. This functions as a pre-made search query and accepts
    URL-friendly search strings. Examples:
    ** alphabet
    ** su:seasons
    ** ti:tractor
    ** nutrition after(2020)
    ** "telling time"
  * URL: Fill in the URL field. Either full URLs (https://example.com) or relative URLs (/eg/kpac/dewey) may be used.
  * Book List: Fill in the Book List ID field. Create a book list in the OPAC and make it shareable. Click "View in
    Catalog" and then copy the bookbag ID from the URL.

=== Additional Customization ===

By default, the KPAC will use the round Evergreen logo. To replace it with a custom logo, replace the file at
/images/kpac2/logo-header.png.

The KPAC utilizes its own CSS files: 

  * /templates-bootstrap/kpac/css/style.css.tt2
  * /templates-bootstrap/kpac/css/colors.tt2
  * /templates-bootstrap/kpac/css/fonts.tt2
  
  


